Щербаков Сергей Вариант 7
frontend-park-mail-ru/homework_2021_2 pull request #10
Opened 2021-08-26 21:05 UTC by F4lkr4m

Done

2021-08-28 11:20 UTC, doomwastaken commented
Привет! Добро пожаловать на курс фронтенда! Я один из менторов и буду проверять твое ДЗ. Обращайся в случае возникновения любых вопросов.

Начну с общих вещей. Молодец что нашел необходимую функцию, язык богат, нет смысла городить свои конструкции. 
Давай сразу добавим jsdoc и дополнительные тесты. 
Я также добавлю пару комментариев к коду.

2021-08-28 11:23 UTC, doomwastaken commented on source/plain.js
> +const plain = arrays => [].concat(...arrays.flat(Infinity));
1) Как думаешь, необходимо ли добавлять дополнительные проверки, покрыты ли граничные условия?
2) Лучше всегда добавлять пустую строку в конец документа.

2021-08-28 11:23 UTC, doomwastaken commented on source/plain.js
> +'use strict'
Опиши в несколько слов зачем нам это необходимо

2021-08-29 19:59 UTC, F4lkr4m commented on source/plain.js
> +'use strict'
Данная директива говорит браузеру обрабатывать скрипт в современном режиме, поскольку js - язык с обратной совместимостью, и когда разработчики языка меняют функционал каких либо функций - меняется и работа скриптов, чтобы код работал как раньше - добавили эту директиву. По сути она запрещает сомнительные решения в языке и собственно разрешает использовать современный функционал.

2021-08-29 20:01 UTC, F4lkr4m commented on source/plain.js
> +const plain = arrays => [].concat(...arrays.flat(Infinity));
1) Думаю да, что-то я как то момент с тестами прошляпил, сейчас добавил :) 
2) Окей)

2021-08-30 05:44 UTC, doomwastaken commented on source/plain.js
> +const plain = arrays => [].concat(...arrays.flat(Infinity));
1)  тут скорее договоренность программистов, безопаснее действительно проверить получил ли ты массив, но в некоторых командах вина лежит на том кто использует инструмент неправильно :)

2021-08-30 05:45 UTC, doomwastaken approved these changes
Все отлично, можно конечно было совсем до 1 строчки сократить, но для меня это более читаемо. Вопросов больше нет, отправляю преподавателям. 

Надеюсь тебе понравиться на курсе фронтенда) Удачи!

2021-08-31 05:16 UTC, doomwastaken requested changes
Доброе утро! Обсудили работу, было решено что использовать flat, конечно, можно, но хочется увидеть свою реализацию именно этой функции, иначе получается слишком просто, а так не интересно!

Пока еще закрытых ПР почти нет, поэтому успеем. Если что пиши в телегу Kostya_Volkov

2021-09-01 05:32 UTC, doomwastaken requested changes
У меня особо вопросов нет

2021-09-01 05:32 UTC, doomwastaken commented on source/plain.js
> +const plain = arrays => {
(не надо исправлять) 
Как думаешь, необходимо ли задавать глубину для работы функции (уровень вложенности), ведь у flat это параметризируемо

2021-09-01 05:32 UTC, doomwastaken commented on source/plain.js
> +        return undefined;
Правильно делаешь что даешь undefined

2021-09-01 05:32 UTC, doomwastaken commented on source/plain.js
> +    let resultArray = [];
В чем различие между let и const, что в этом случае необходимо использовать?

2021-09-01 05:32 UTC, doomwastaken commented on source/plain.js
> +    arrays.forEach(function(item) {
если делали стрелочные функции, то давай все сделаем в одном стиле

2021-09-01 09:58 UTC, F4lkr4m commented on source/plain.js
> +const plain = arrays => {
Зависит от функционала и требований программы, возможно понадобится когда то не полностью поднимать наверх вложенные массивы, тогда и понадобится задание глубины.

2021-09-01 09:58 UTC, F4lkr4m commented on source/plain.js
> +const plain = arrays => {
Зависит от функционала и требований программы, возможно понадобится когда то не полностью поднимать наверх вложенные массивы, тогда и понадобится задание глубины.

2021-09-01 10:00 UTC, F4lkr4m commented on source/plain.js
> +    let resultArray = [];
Принцип инициализации переменных одинаковый в отличии let и var. Но вот только const создает переменную константную, которую нельзя изменять, let же современный метод инициализации обычной переменной

2021-09-01 11:18 UTC, doomwastaken commented on source/plain.js
> +    let resultArray = [];
а что нам все же нужно в данном случае?

2021-09-01 11:46 UTC, doomwastaken commented on source/plain.js
> +    let resultArray = [];
И вот тут можно освежить понимание насчет let/const. Пока ты сам линтер для кода) 
https://habr.com/ru/post/482892/

2021-09-01 14:21 UTC, F4lkr4m commented on source/plain.js
> +    let resultArray = [];
Материал усвоен)

2021-09-01 15:02 UTC, doomwastaken approved these changes
С моей стороны больше никаких замечаний

2021-09-01 21:14 UTC, Betchika99 requested changes

2021-09-01 21:14 UTC, Betchika99 commented on source/plain.js
> + * @param {array} arrays with inner arrays
типа array в JSDoc нет. Пруф [здесь](https://jsdoc.app/tags-param.html)

2021-09-01 21:14 UTC, Betchika99 commented on source/plain.js
> +const plain = arrays => {
по код стайлу параметры стрелочных функций лучше оборачивать в круглые скобки

2021-09-01 21:14 UTC, Betchika99 commented on source/plain.js
> +    return resultArray;
попробуй использовать для этого перебирающий метод для массивов reduce. Ведь ты как раз накапливаешь результат

2021-09-01 21:14 UTC, Betchika99 commented on source/plain.js
> +        Array.isArray(item) ? Array.prototype.push.apply(resultArray, plain(item)) : resultArray.push(item);
рекурсивные функции на клиенте - очень дорогие функции. давай попробуем избавить от рекурсии

2021-09-01 21:14 UTC, Betchika99 commented on tests/plain.js
> +		assert.deepEqual(plain(123), undefined);
можно еще проверить на null и undefined. А еще например на [null, undefined]

2021-09-02 07:33 UTC, F4lkr4m commented on tests/plain.js
> +		assert.deepEqual(plain(123), undefined);
Я добавил тест, относящийся к работе с типами, думаю если хотят, то пусть передают [null, undefined]. В плане глубже делать проверку на undefined и null не имеет смысла, в этом может быть заложена логика.

2021-09-02 07:43 UTC, F4lkr4m commented on source/plain.js
> +    return resultArray;
Ну тут вроде как то по особенному не нужно обрабатывать элемент на основе предыдущих результатов, или может я не правильно понял мысль(

2021-09-02 21:31 UTC, closed without merging