Кравцов Андрей Вариант 18
frontend-park-mail-ru/homework_2021_2 pull request #12
Opened 2021-08-27 16:27 UTC by kravtandr

2021-08-28 09:54 UTC, alexey-ershkov requested changes
Привет!) Поздравляю с переходом на второй семестр) Приветствую на курсе фронтенд разработки) Будет интересный семестр) У тебя хорошее решение, но есть пара правок)

2021-08-28 09:54 UTC, alexey-ershkov commented on index.html
> +<script src="source/solve.js"></script>
Хорошо бы дописать еще несколько паков тестов к твоей функции)

2021-08-28 09:54 UTC, alexey-ershkov commented on source/solve.js
> +'use strict';
Можешь рассказать что это такое и для чего нужно?

2021-08-28 09:54 UTC, alexey-ershkov commented on source/solve.js
> +let solve = (expression, arg) =>  eval(expression.replace(/x/g, arg));
Ставлю лайк за лаконичное решение, но использовать eval очень небезопасно  - давай избавимся от него. Думаю, что тебе может помочь использование методов массива. Почитать про них можешь  [здесь](https://learn.javascript.ru/array-methods). 

Также давай воспользуемся JSDoc,  чтобы описать что делает функция, какие у нее входные и выходные параметры.

А что, если `arg` - это не число - а, например, undefined или строка? Что будет, если `expression` окажется пустым? Давай покроем эти случаи тестами

2021-08-30 12:58 UTC, alexey-ershkov requested changes

2021-08-30 12:58 UTC, alexey-ershkov commented on jsdoc.json
> +  }
Много файлов от ide, закинь из в gitignore и удали из коммита

2021-08-30 12:58 UTC, alexey-ershkov commented on source/solve.js
> +    var methods = {
Почему здесь `var`? Если объект не меняется, то лучше использовать const. Также мб вынести объект с методом за рамки функции?

2021-08-30 12:58 UTC, alexey-ershkov commented on source/solve.js
> +    while(expression.indexOf(")") != -1){
-1 - магическая константа

2021-08-30 12:58 UTC, alexey-ershkov commented on tests/solve.js
> +});
Нет переноса на новую строку в конце

2021-08-30 12:58 UTC, alexey-ershkov commented on .gitignore
> +docs/
Нет переноса на новую строку в конце

2021-08-30 12:58 UTC, alexey-ershkov commented on source/solve.js
> +        let split = substr.split(' ').filter(item => item != ''),
Давай избавимся здесь от оператора `,`, и сделаем код более читаемым. Имхо split не оч отражает смысл. Мб подумаешь еще над названием?

2021-08-30 12:58 UTC, alexey-ershkov commented on source/solve.js
> +        let substr = expression.slice(leftBracketPos+1, rightBracketPos);
Аналогично split не оч название

2021-08-30 12:58 UTC, alexey-ershkov commented on source/solve.js
> +        if (!methods[op] || isNaN(a) || isNaN(b)) {
Это повторяющаяся проверка - вынеси ее в отдельную функцию

2021-08-30 12:58 UTC, alexey-ershkov commented on source/solve.js
> +    expression = expression.split(' ').filter(item => item != '')
сплит + фильтр повторяются - вынеси в функцию

2021-08-31 09:27 UTC, alexey-ershkov requested changes
Жду еще ответ на вопрос по use strict

2021-08-31 15:56 UTC, kravtandr commented on source/solve.js
> +'use strict';
Эта директива нужна, чтобы активировать режим обратной совместимости кода, который был написан до того как вышел ES5.

2021-08-31 16:01 UTC, alexey-ershkov commented on source/solve.js
> +'use strict';
С точностью до наоборот) Обратная совместимость есть из коробки, чтобы использовать новую функциональность es5, как раз нужно написать эту директиву. Можешь почитать подробнее [здесь](https://learn.javascript.ru/strict-mode)

2021-08-31 16:02 UTC, alexey-ershkov approved these changes

2021-09-01 21:36 UTC, alexey-ershkov requested changes
Добрый вечер) Прости, поторопился с аппрувом. Нашел еще несколько важных замечаний, которые нужно исправить

2021-09-01 21:36 UTC, alexey-ershkov commented on source/solve.js
> +    if (expression == ''|| expression == undefined || isNaN(arg)) {
Почему делаешь нестрогие сравнения? Подробнее можешь почитать [здесь](https://learn.javascript.ru/comparison)

2021-09-01 21:45 UTC, alexey-ershkov commented on source/solve.js
> +        leftBracketPos = expression.slice(0,rightBracketPos).lastIndexOf("(");
То одинарные, то двойные скобки - давай выдержим единый стиль кода. Почитать можешь [здесь](https://learn.javascript.ru/coding-style)

2021-09-04 10:04 UTC, alexey-ershkov requested changes

2021-09-04 10:04 UTC, alexey-ershkov commented on source/solve.js
> + * @returns {String} - postfix expression string
Почему из этого метода не вернуть массив? Чтобы дважды не разбивать по пробелам

2021-09-04 10:04 UTC, alexey-ershkov commented on tests/solve.js
> +		assert.strictEqual(isNaN(solve(undefined, 2)), true)
Негативные тесты лучше вынести в отдельный модуль

2021-09-04 11:12 UTC, alexey-ershkov commented on tests/solve_negative.js
> +QUnit.module('Дополнительно тестируем функцию solve c негативными тестами', function () {
Имелось ввиду QUnit.module в том же файле

2021-09-04 12:24 UTC, alexey-ershkov requested changes

2021-09-04 12:24 UTC, alexey-ershkov commented on source/solve.js
> +    let postfix = expression.reduce((acc, item) => {
то, что нужно - данные из акумулятора можно сразу получить деструктуризацией объекта - `({postfixExpression, stack}, item) => ...`

И опять `const`

2021-09-04 12:24 UTC, alexey-ershkov commented on source/solve.js
> + * @returns {(number|string)} - postfix expression array
Так ты же массив возвращаешь, тогда уж `Array<number|string>`

2021-09-04 12:24 UTC, alexey-ershkov commented on source/solve.js
> + * @returns {(number|string)} - formated operation Array
Аналогично здесь с типом массива

2021-09-04 12:24 UTC, alexey-ershkov commented on source/solve.js
> +    expression.forEach((item) => {
Здесь тоже reduce нужен

2021-09-04 12:24 UTC, alexey-ershkov commented on source/solve.js
> +        return 1;
Не исправлено

2021-09-04 12:24 UTC, alexey-ershkov commented on source/solve.js
> +const ExpressionToPostfix = (expression) => {
не исправлено название

2021-09-04 13:11 UTC, alexey-ershkov requested changes

2021-09-04 13:11 UTC, alexey-ershkov commented on source/solve.js
> +
Лишняя строка

2021-09-04 13:15 UTC, alexey-ershkov requested changes

2021-09-04 13:15 UTC, alexey-ershkov commented on source/solve.js
> +            let [b, a] = [stack.pop(), stack.pop()];
Тоже const

2021-09-04 14:01 UTC, closed without merging