Variant 4
frontend-park-mail-ru/homework_2021_2 pull request #13
Opened 2021-08-27 19:45 UTC by Shureks-den

Клонов Александр, АПО-21

2021-09-01 21:30 UTC, Betchika99 requested changes
привет) нужно разобраться, когда используются let/const/var. В твоем коде они используются некорректно. Также нужно поправить код в соответствии [код стайлу](https://learn.javascript.ru/coding-style) и исправить некоторые замечания

2021-09-01 21:30 UTC, Betchika99 commented on source/inverse.js
> +    let arrayCopy = array.slice(); // создаем копию чтобы не ломать исходный массив
это не копия на массив, а копия ссылки на массив. То есть ты в любом случае меняешь исходный. Нужно сделать настоящую копию, чтобы функция оставалась чистой

2021-09-01 21:30 UTC, Betchika99 commented on source/inverse.js
> +let inverse = (array, start = 0) => {
почему здесь используется let в качестве идентификатора? разве функция будет меняться где-то?

2021-09-01 21:30 UTC, Betchika99 commented on source/inverse.js
> +    let reversedPart = start > 0 ? arrayCopy.splice(start, arrayCopy.length) : arrayCopy.splice(0, arrayCopy.length + start);
эта строчка очень длинная. Перенеси красиво части тернарного оператора

2021-09-01 21:43 UTC, Xatabch commented on source/inverse.js
> +    let arrayCopy = array.slice(); // создаем копию чтобы не ломать исходный массив
Не, это копия,  чек mds https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/slice )

2021-09-01 22:10 UTC, Betchika99 commented on source/inverse.js
> +    let arrayCopy = array.slice(); // создаем копию чтобы не ломать исходный массив
почему только символы? там же любые элементы могут быть. И энивей лучше делать функцию чистой, чтобы в какой-то поздний момент не обнаружить ошибку в таком месте

2021-09-01 22:13 UTC, Xatabch commented on source/inverse.js
> +    let arrayCopy = array.slice(); // создаем копию чтобы не ломать исходный массив
а, и правда любые, да, тогда все ок

2021-09-02 20:19 UTC, Shureks-den commented on source/inverse.js
> +    let arrayCopy = array.slice(); // создаем копию чтобы не ломать исходный массив
Не очень понял, что тут нужно поправить. Мне нужно сделать deep copy всех объектов в массиве?

2021-09-02 21:08 UTC, Shureks-den commented
Добавил отдельную функцию для копирования, я прочитал, что spread делает тоже самое, что и slice
![image](https://user-images.githubusercontent.com/65308659/131916432-ccbc3dec-3d50-4a74-8fc1-ab8a2cd3ecaf.png)

2021-09-03 11:20 UTC, closed without merging