Ксения Самойлова
frontend-park-mail-ru/homework_2021_2 pull request #14
Opened 2021-08-27 21:26 UTC by somebody-kseny

2021-08-28 09:40 UTC, alexey-ershkov requested changes
Привет) Поздравляю с переходом на второй семестр технопарка) Добро пожаловать на курс фронтенд разработки! Я написал тебе несколько правок) Ставлю отдельный лайк за стрелочные функции

2021-08-28 09:40 UTC, alexey-ershkov commented on source/euclid.js
> +'use strict';
Можешь рассказать что это и для чего используется?

2021-08-28 09:40 UTC, alexey-ershkov commented on source/euclid.js
> +const findNOD = (a, b) => {
Давай воспользуемся JSDoc и опишем что делает функция, что принимает и возвращает

2021-08-28 09:40 UTC, alexey-ershkov commented on source/euclid.js
> +}
Нет переноса строки в конце

2021-08-28 09:40 UTC, alexey-ershkov commented on source/euclid.js
> +const euclid = (...numbers) => {
Аналогично здесь добавим JSDoc

2021-08-28 09:40 UTC, alexey-ershkov commented on tests/euclid.js
> +		assert.strictEqual(euclid(1, 8), 1, 'euclid(1) === 1');
Эти тесты менять не нужно)

2021-08-28 09:40 UTC, alexey-ershkov commented on source/euclid.js
> +    let prev_nod = numbers[0];
А если массив пустой? + такой случай имеет смысл покрыть тестами

2021-08-28 09:40 UTC, alexey-ershkov commented on source/euclid.js
> +    for (let i = 1; i < numbers.length; i++){
Давай упростим это с помощью методов массива. Почитать про них можешь [здесь](https://learn.javascript.ru/array-methods)

2021-08-28 09:40 UTC, alexey-ershkov commented on tests/euclid.js
> +	QUnit.test('Функция должна правильно находить НОД двух натуральных чисел тоже', function (assert) {
А что будет, если на вход придет набор их разных типов данных? Например euclid('2', undefined, null, 56). Кажется подобные краевые случаи есть смысл покрыть отдельным паком тестов

2021-08-28 10:00 UTC, alexey-ershkov commented on source/euclid.js
> +    while ( (a != 0) && (b != 0) ) {
Подумай как можно назвать переменные `a` и `b`

2021-09-01 08:49 UTC, alexey-ershkov requested changes

2021-09-01 08:49 UTC, alexey-ershkov commented on source/euclid.js
> +    if ( (isNaN(left)) || (isNaN(right)) || (left == null) || (right == null)) {
Почему не используешь строгое сравнение? Подробнее об этом можно почитать [здесь](https://learn.javascript.ru/comparison#strogoe-sravnenie)

2021-09-01 08:49 UTC, alexey-ershkov commented on source/euclid.js
> +    while(numbers.length > 0){
Сюда просится `forEach`

2021-09-01 21:11 UTC, alexey-ershkov approved these changes

2021-09-01 21:57 UTC, alexey-ershkov requested changes
Привет) Прости, поторопился с аппрувом) Тут еще пара замечаний

2021-09-01 21:57 UTC, alexey-ershkov commented on source/euclid.js
> +const findNOD = (left, right) => {
Нигде нет точек с запятой и принято писать названия в camelCase - подробнее можешь посмотреть про это [здесь](https://learn.javascript.ru/coding-style)

2021-09-02 12:52 UTC, somebody-kseny commented
Я поменяла местами две функции (почитала подробнее там), поэтому  изменения коммита показываются некрасиво

2021-09-02 13:06 UTC, alexey-ershkov requested changes
Еще небольшие правки

2021-09-02 13:06 UTC, alexey-ershkov commented on source/euclid.js
> +'use strict'; // Это директива, которая заставляет использовать новый (5-й),
Как правило комментарии пишутся над тем, к чему они относятся

2021-09-03 07:36 UTC, alexey-ershkov requested changes

2021-09-03 07:36 UTC, alexey-ershkov commented on source/euclid.js
> +  * @returns { (number|undefined) } - число, НОД, если на вход поданы натуральные числа.
Здесь скобки не нужны

2021-09-03 07:36 UTC, alexey-ershkov commented on source/euclid.js
> +  * @returns { (number|undefined) } - число, НОД, если на вход поданы два натуральных числа.
Здесь скобки тоже не нужны

2021-09-03 07:36 UTC, alexey-ershkov commented on source/euclid.js
> +    if (  typeof left !== "number"  ||  typeof right !== "number"  ) {
кодстайл - отступ от скобки два пробела, ранее ни одного, позже 1 - приведи к единому стилю. Давай приведем код к единому стилю - можешь посмотреть правила [JS Standart](https://github.com/standard/standard/blob/master/RULES.md)

2021-09-04 07:51 UTC, alexey-ershkov requested changes

2021-09-04 07:51 UTC, alexey-ershkov commented on source/euclid.js
> +  let currentNod = numbers[0];
Сюда прям просится `reduce`

2021-09-04 07:51 UTC, alexey-ershkov commented on source/euclid.js
> + *     Иначе - undefined
Зачем отступы?

2021-09-04 08:10 UTC, alexey-ershkov approved these changes

2021-09-04 08:27 UTC, closed without merging