Попов Михаил
frontend-park-mail-ru/homework_2021_2 pull request #15
Opened 2021-08-28 05:03 UTC by 4Marvin2

2021-08-28 17:08 UTC, Slava-Romanov requested changes
Привет! Добро пожаловать на курс по фронтенду :) Сейчас я буду проверять твое нулевое дз. Если возникнут вопросы, не стесняйся, пиши в тг: @Slava_Romanov

2021-08-30 16:53 UTC, 4Marvin2 commented on source/solve.js
> +'use strict';
use strict включает строгий режим, который позволяет исключить некоторые опасные выражения js.

2021-08-30 19:16 UTC, Slava-Romanov requested changes
Добавил несколько замечаний

2021-08-30 19:16 UTC, Slava-Romanov commented on tests/solve.js
> +		assert.strictEqual(solve('x + (x - 3))', 2), "Ошибка в выражении");
На ''x^100' тоже(

2021-08-30 19:16 UTC, Slava-Romanov commented on tests/solve.js
> +		assert.strictEqual(solve('x + (x - 3))', 2), "Ошибка в выражении");
Что будет, если выражение x будет некорректным?

2021-08-31 21:31 UTC, Slava-Romanov requested changes

2021-08-31 21:31 UTC, Slava-Romanov commented on source/solve.js
> +        throw new TypeError('Invalid type of expression');
?

2021-08-31 21:31 UTC, Slava-Romanov commented on source/solve.js
> +const operations = (operator, firstArgument, secondArgument) => {
Что будет, если operator не будет равен ни одному из 4-ех указанных вариантов? Не требуется ли тут null?

2021-08-31 21:31 UTC, Slava-Romanov commented on source/solve.js
> +const toRPN = (expression) => {
возможно в названии также нужно указать из какой формы происходит перевод

2021-08-31 21:31 UTC, Slava-Romanov commented on source/solve.js
> +        return SYNTAX_ERROR;
Можно так же, как и в другой функции throw new TypeError, чтобы вызывая эту функцию было сразу понятно, что что-то не так, а не пытаться работать с полученным значением

2021-08-31 21:31 UTC, Slava-Romanov commented on source/solve.js
> +        return SYNTAX_ERROR;
И тогда в тестах будет проверка через assert.throws

2021-08-31 21:31 UTC, Slava-Romanov commented on tests/solve.js
>  	});
solve(5, 5) выдает что-то странное?

2021-08-31 21:31 UTC, Slava-Romanov commented on tests/solve.js
>  	});
solve('()', 5)

2021-08-31 21:31 UTC, Slava-Romanov commented on tests/solve.js
>  	});
solve('( + )', 5)

2021-08-31 21:31 UTC, Slava-Romanov commented on tests/solve.js
>  	});
solve('x x x', 5)

2021-08-31 21:31 UTC, Slava-Romanov commented on tests/solve.js
> +		assert.strictEqual(solve('x + (x - 3))', 2), EXPRESSION_ERROR);
Давай добавим тут еще тестов

2021-09-04 10:09 UTC, Slava-Romanov requested changes

2021-09-04 22:44 UTC, Slava-Romanov approved these changes

2021-09-05 12:21 UTC, closed without merging