Рудых Евгений
frontend-park-mail-ru/homework_2021_2 pull request #16
Opened 2021-08-28 15:32 UTC by Lyalyashechka

2021-08-28 16:06 UTC, Slava-Romanov requested changes
Привет! Добро пожаловать на курс по фронтенду :) Сейчас я буду проверять твое нулевое дз. Если возникнут вопросы, не стесняйся, пиши в тг: @Slava_Romanov

2021-08-30 17:37 UTC, Slava-Romanov commented on source/plain.js
> +'use strict';
?

2021-08-30 18:32 UTC, Slava-Romanov requested changes
Написал небольшие комментарии, исправь их и все) Также пожалуйста ответь на вопрос про использование strict

2021-08-30 18:32 UTC, Slava-Romanov commented on source/plain.js
> +        return null;
Может стоит возвращать undefined?
<img width="274" alt="image" src="https://user-images.githubusercontent.com/56159458/131382630-292ee97a-ab56-4d58-9fc0-ce881d99023e.png">

2021-08-30 18:32 UTC, Slava-Romanov commented on tests/plain.js
> +	QUnit.test('Работа с не массивом', function(assert) {
Давай добавим тест с объектом во входных данных

2021-08-30 18:32 UTC, Slava-Romanov commented on tests/plain.js
> +	QUnit.test('Работа с не массивом', function(assert) {
И с объектами внутри массива

2021-08-30 18:32 UTC, Slava-Romanov commented on source/plain.js
> +    if (Array.isArray(arr)) {
Обычно return некорректных данных идет выше. За счет этого код можно сделать чуть короче и без else

2021-09-01 06:43 UTC, Lyalyashechka commented on source/plain.js
> +'use strict';
Привет. Директива "use strict" активирует новые возможности и изменения языка в ES5. И чтобы устаревший код работал, как и раньше, по умолчанию подобные изменения не применяются.

2021-09-02 23:29 UTC, Slava-Romanov requested changes
Требуется последний штрих

2021-09-02 23:29 UTC, Slava-Romanov commented on source/plain.js
> + * @returns {null} если на вход передан не массив
Здесь представлено два блока returns, должен быть один, но при этом должно быть описано оба случая

2021-09-02 23:29 UTC, Slava-Romanov commented on source/plain.js
> +        return undefined;
Все-таки тут нужен return null. Если ты заменил из-за прошлого комментария, извини, я его почти сразу удалил, так как при undefined не полностью очевидно: а что пошло не так

2021-09-02 23:29 UTC, Slava-Romanov commented on source/plain.js
> +const plain = arr => {
Здесь небольшая путаница блочного и строчного стиля

2021-09-04 11:25 UTC, closed without merging