Камила Нурхаметова
frontend-park-mail-ru/homework_2021_2 pull request #18
Opened 2021-08-28 20:09 UTC by imkamie

2021-08-29 12:33 UTC, Alkirys commented
Привет и добро пожаловать на 2 семестр Технопарка! Я буду проверять твое нулевое дз по фронтенду, так что в случае возникновения вопросов не стесняйся писать) Мой ник в телеге @Alkirys.

У меня есть несколько комментариев по коду, но в целом могу сказать, что ты отлично поработала. Отдельный респект за использование JsDoc и встроенных методов массивов👍

2021-08-29 12:51 UTC, Alkirys commented on source/format.js
> +'use strict';
Круто, что ты знаешь про 'use strict', расскажи, для чего оно нужно?

2021-08-29 12:51 UTC, Alkirys commented on source/format.js
> +    input.forEach(function callback(element, index) {
В коде выше ты используешь стрелочные функции, а здесь почему-то нет. Почему?)

2021-08-29 12:51 UTC, Alkirys commented on source/format.js
> +		result += ' '.repeat(numberOfSpaces) + element + ((column === columns - 1) ? '\n' : ' ');
Кажется, тут отступы поехали 🙃

2021-08-29 12:51 UTC, Alkirys commented on source/format.js
> +    let columnWidth = new Array();
Тут вместо new Array() можно написать просто [], выйдет немного лаконичнее

2021-08-29 12:51 UTC, Alkirys commented on source/format.js
> +}
Здесь(и не только) лучше добавить перенос строки в конце файла

2021-08-29 12:51 UTC, Alkirys commented on source/format.js
> +		let numberOfSpaces = columnWidth[column] - element.length;
А почему ты используешь в этом месте let?

2021-08-29 12:51 UTC, Alkirys commented on source/format.js
> +}
И ; забыла)

2021-08-29 12:51 UTC, Alkirys commented on tests/format.js
> +		assert.throws(() => format([], 1));
Что случится, если передать вместо массива null или undefined?

2021-08-29 16:46 UTC, imkamie commented on source/format.js
> +'use strict';
Благодаря 'use strict' код js обрабатывается в строгом режиме. В строгом режиме некоторые ошибки заменяются исключениями, что помогает их быстрее и легче найти; в строгом режиме в некоторых случаях код может быть оптимизирован и выполняться будет быстрее; строгий режим запрещает использование некоторых элементов синтаксиса.

2021-08-29 16:57 UTC, Alkirys commented on source/format.js
> +    let columnWidth = [];
Здесь тоже лучше использовать const

2021-08-29 16:57 UTC, Alkirys commented on tests/format.js
> +		assert.throws(() => format(undefined, 1));
Эти тесты не работают. Проверь эти 2 случая вручную)

2021-08-29 16:57 UTC, Alkirys commented on source/format.js
> +    let columnWidth = [];
Почему так можно сделать понимаешь?

2021-08-29 16:59 UTC, Alkirys commented on source/format.js
> +    if (columns <= 0 || input.length === 0 || !Array.isArray(input) || input.some(element => typeof element !== "number")) {
В js используются одинарные кавычки, не забывай)

2021-08-29 17:29 UTC, imkamie commented on source/format.js
> +    let columnWidth = [];
Потому что const задаётся самой переменной, но не содержимому в ней. То есть изменять содержимое массива я могу, но сам массив приравняться например строке уже не могу. То же самое работает и для объектов.

2021-08-29 18:53 UTC, Alkirys commented on source/format.js
> +        input === null || input === undefined)) {
В javascript примитивные типы автоматически кастятся в bool

2021-08-29 18:53 UTC, Alkirys commented on source/format.js
> +        input.some(element => typeof element !== 'number' ||
Мне кажется, лучше вынести эту проверку в функцию, которую ты передаешь в map, чтобы 2 раза не проходиться по массиву

2021-08-29 18:58 UTC, Alkirys commented on source/format.js
> +        input.some(element => typeof element !== 'number' ||
И обрати внимание: в условии задачи сказано, что функция должна форматировать целые числа, так что, лучше использовать другую проверку(обрати внимание на методы объекта Number)

2021-08-29 20:46 UTC, Alkirys commented on source/format.js
> +function isElementInteger(element) {
JSDoc не для той функции. Будь повнимательней)

2021-08-29 20:46 UTC, Alkirys commented on source/format.js
> +function isElementInteger(element) {
Стрелочные функции - стильно, модно, молодежно. Используй лучше их)

2021-09-02 07:53 UTC, Alkirys commented
Привет! Мне тут сказали, что нужно уделять больше внимания синтаксису и некоторым другим вещам, так что, у меня есть еще несколько замечаний по твоему коду

2021-09-02 07:56 UTC, Alkirys requested changes

2021-09-02 07:56 UTC, Alkirys commented on source/format.js
> + * @returns {Boolean}
Давай добавим в этом месте описание для @returns

2021-09-02 07:56 UTC, Alkirys commented on source/format.js
> +            return item.toString();
Изменять исходные данные - плохая практика. Лучше, чтобы функция была чистой

2021-09-02 17:48 UTC, Alkirys requested changes

2021-09-02 17:48 UTC, Alkirys commented on source/format.js
> +    const inputWithStrings = input.map(item => {
По кодстайлу все параметры стрелочных функций лучше обрамлять круглыми скобками

2021-09-02 19:19 UTC, Betchika99 requested changes

2021-09-02 19:19 UTC, Betchika99 commented on source/format.js
> +    });
Здесь можно использовать перебирающий метод массивов reduce для накопления columnWidth

2021-09-02 23:42 UTC, Alkirys commented on source/format.js
> +    }, new Array(columns));
Можно использовать синтаксис []

2021-09-02 23:42 UTC, Alkirys commented on source/format.js
> +    const columnWidth = inputWithStrings.reduce((accumulator, element, index) => {
Дай переменным более развернутые имена

2021-09-03 00:06 UTC, Alkirys commented on source/format.js
> + * @returns {Boolean} - возвращает true, если аргумент является целым числом
Посмотри [тут,](https://jsdoc.app/tags-param.html) как правильно обозначать массивы в JSDoc

2021-09-03 10:42 UTC, Alkirys approved these changes

2021-09-03 11:01 UTC, closed without merging