Самойлов Алексей
frontend-park-mail-ru/homework_2021_2 pull request #19
Opened 2021-08-28 20:19 UTC by tr0llex

группа АПО-21
**Вариант #19**

2021-08-29 08:11 UTC, zelflod requested changes
Приветствую на курсе фронтенда!

2021-08-29 08:11 UTC, zelflod commented on source/zip.js
> +function zip() {
Получилось работающее решение, но можно написать лучше используя современные возможности JS и функциональный стиль
Таким образом не будет неопходимости в arguments, переменной concatenation, двух циклах for, двух if'ов и проверки key in concatenation

2021-08-29 08:11 UTC, zelflod commented on source/zip.js
> +    for (var i = 0; i < arguments.length; i++) {
чем rest параметры лучше псевдомассива arguments можно узнать в https://learn.javascript.ru/rest-parameters-spread-operator

2021-08-29 08:11 UTC, zelflod commented on source/zip.js
> +    for (var i = 0; i < arguments.length; i++) {
вместо циклов for можно использовать различные стандартные методы массивов https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array#
hint: тебе нужно из множества элементов массива получить один итоговый результа, для этого есть специальный метод)

2021-08-29 08:11 UTC, zelflod commented on source/zip.js
> +            }
вместо всего этого есть Object.assign https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign
но лучше использовать object spread https://www.javascripttutorial.net/es-next/javascript-object-spread/

2021-08-29 08:11 UTC, zelflod commented on source/zip.js
> +        if (typeof arguments[i] == "object") {
такс, тут ты фильтруешь элементы массива, правильно
еще погугли "js array filter"

2021-08-29 18:28 UTC, zelflod commented on source/zip.js
> +    return Object.assign({}, ...objects.reverse());
можно было еще reduce ипользовать

2021-08-29 18:32 UTC, tr0llex commented on source/zip.js
> +    return Object.assign({}, ...objects.reverse());
Нужно переделать?

2021-08-29 18:52 UTC, zelflod commented on source/zip.js
> +    return Object.assign({}, ...objects.reverse());
да, давай редюс добавим

2021-08-29 19:16 UTC, tr0llex commented on source/zip.js
> +    return Object.assign({}, ...objects.reverse());
Готово

2021-08-29 19:21 UTC, zelflod requested changes

2021-08-29 19:21 UTC, zelflod commented on source/zip.js
> +    objects = objects.filter(obj => typeof obj == 'object');
давай не создавать переменную objects, сразу делай return object.filter.reduceRight, так можно)

2021-08-29 19:22 UTC, zelflod commented on source/zip.js
> +    return Object.assign({}, ...objects.reverse());
оставил еще одно замечание)

2021-08-29 19:37 UTC, tr0llex commented on source/zip.js
> +    objects = objects.filter(obj => typeof obj == 'object');
Готово

2021-08-29 19:39 UTC, zelflod approved these changes

2021-08-30 14:42 UTC, zelflod commented on source/zip.js
> +    return objects.filter(obj => typeof obj == 'object').reduceRight((res, cur) => ({...res, ...cur}), {});
йоу, забыл оставить замечание по https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Strict_equality
в основном используют строгое равенство, потому что оно более предсказуемое

2021-08-30 15:05 UTC, tr0llex commented on source/zip.js
> +    return objects.filter(obj => typeof obj == 'object').reduceRight((res, cur) => ({...res, ...cur}), {});
привет, знаю, читал, здесь это не критично, потому что typeof всегда возвращает строку

2021-09-02 09:49 UTC, Betchika99 requested changes

2021-09-02 09:49 UTC, Betchika99 commented on source/zip.js
> + * @returns {Object} возвращает объект, содержащий все поля из всех переданных объектов
Типа Object в JSDoc нет, посмотри повнимательнее

2021-09-02 09:49 UTC, Betchika99 commented on source/zip.js
> + * Объединить объекты
Не хватает информации в JSDoc про то, какие параметры функция принимает

2021-09-02 09:49 UTC, Betchika99 commented on source/zip.js
> +function zip(...objects) {
Почему здесь тоже не использовать стрелочную функцию?

2021-09-02 09:49 UTC, Betchika99 commented on source/zip.js
> +    return objects.filter(obj => typeof obj == 'object').reduceRight((res, cur) => ({...res, ...cur}), {});
null - это тоже тип object

2021-09-02 09:49 UTC, Betchika99 commented on source/zip.js
> +    return objects.filter(obj => typeof obj == 'object').reduceRight((res, cur) => ({...res, ...cur}), {});
Это строка очень длинная и тяжело читается. Давай немного ее разобьём

2021-09-03 20:27 UTC, closed without merging