Ершов Виталий - Вариант 13
frontend-park-mail-ru/homework_2021_2 pull request #2
Opened 2021-08-25 09:23 UTC by VErshovBMSTU

2021-08-28 08:34 UTC, zelflod requested changes
Приветствую тебя на курсе фронтенда! Я ментор на курсе, буду проверять дз и помогать решать любые другие вопросы в течение семестра 

Оставил несколько комментов, исправь пожалуйста и снова отдай в ревью

PS. Ты потрогал очень много файлов, которых можно (нужно!) было не трогать, из-за чего ревьють неудобно. В идеале у тебя должны быть изменены всего лишь три файла, а не 25)

2021-08-28 08:34 UTC, zelflod commented on tests/get.js
> +	QUnit.test('Custom tests', function (assert) {
Может лучше дать семантически правильное название тесту, чтобы было понятно что проверяется

2021-08-28 08:34 UTC, zelflod commented on source/get.js
> +    if (key.length === 1)
А что будет если key - undefined? Провалидируй плиз аргументы и добавь тесты, например для `get()`, `get(object)`, `get(object, null)`, `get(null, 1234)` и тд

2021-08-28 08:34 UTC, zelflod commented on source/get.js
> +    if (key.length === 1)
Нужно гарантировать что функция не сломается если передать ей невалидное значение

2021-08-28 08:34 UTC, zelflod commented on source/get.js
> +const get = (object, key) => {
Может добавим jsdoc для функции, чтобы было понятнее  что она делает

2021-08-28 08:34 UTC, zelflod commented on source/get.js
> +    for (let index = 1; index < keys.length; ++index) {
Если воспользоваться стандартными функция JS https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array#, то код будет красивее

2021-08-28 08:34 UTC, zelflod commented on tests/get.js
> +		assert.strictEqual(get(object, '.0.deep'), object["0"].deep);
давай попробуем еще 
```js
assert.strictEqual(get(object, '.0.deep.somekey'), undefined);
```

2021-08-28 08:34 UTC, zelflod commented on source/get.js
> +       if (typeof object === 'undefined') {
Раз. object может быть не объект и не undefined, например число 1. Тогда мы не попадем в этот if

2021-08-28 08:34 UTC, zelflod commented on source/get.js
> +       object = object[ keys[ index ] ];
Два. если object был числом и ранее мы не попали в if, то тут мы пытаемся получить поле `keys[index]` у числа. Нас ожидает сюрприз в виде ошибки)

2021-08-28 08:34 UTC, zelflod commented on source/get.js
> +       object = object[ keys[ index ] ];
Учти плиз что значением может быть все что угодно и правильно обработай такой кейс

2021-08-28 11:18 UTC, zelflod commented on source/get.js
> +    if (key.length === 1)
Если `get(object, 'a')`, то возвращается сам объект. Не соответствует условию задачи и в принципе нелогично выглядит

2021-08-28 11:45 UTC, zelflod requested changes

2021-08-28 11:45 UTC, zelflod commented on source/get.js
> +        return object;
Если `get(object, 'a')`, то возвращается сам объект. Не соответствует условию задачи и в принципе нелогично выглядит

2021-08-28 11:45 UTC, zelflod commented on source/get.js
> +    (key.substring(1)).split('.').forEach(function(item, i, keys) {
Если первый символ ключа не точка (ранее никак это у тебя не проверяется), то получается отрезаем произвольный символ

2021-08-28 11:45 UTC, zelflod commented on source/get.js
> +            object = object[ keys[ i ] ];
вместо `keys[ i ]` можно использовать `item`

2021-08-28 11:45 UTC, zelflod commented on tests/get.js
> +		assert.strictEqual(get(object, '.3'), object["3"]);
Попробуй добавить в object еще одно поле bar:
```js
const object = {
          ...
	          bar: {
		          1: null
	          }
          ...
          };
```

и проверку
```js
assert.strictEqual(get(object, '.bar.1'), null);
assert.strictEqual(get(object, '.bar.1.somekey'), undefined);
```

2021-08-28 17:04 UTC, zelflod requested changes

2021-08-28 17:12 UTC, zelflod approved these changes

2021-09-01 18:31 UTC, Betchika99 requested changes

2021-09-01 22:07 UTC, closed without merging