Журавлев Николай
frontend-park-mail-ru/homework_2021_2 pull request #22
Opened 2021-08-29 16:07 UTC by a1i5k

2021-08-30 09:14 UTC, Sarafa2n requested changes
Привет! Поздравляю тебя с переходом на второй семестр и добро пожаловать на курс фронтенда! У тебя неплохое решение, но есть пару замечаний. Давай напишем еще тесты. К примеру на неправильные данные.

2021-08-30 09:14 UTC, Sarafa2n commented on source/format.js
> +'use strict';
А зачем это нужно?

2021-08-30 09:14 UTC, Sarafa2n commented on source/format.js
> +const format = function (numbers, col) {
А давай сделаем по молодежному, используй другой способ)
И давай добавим JSDoc

2021-08-30 09:14 UTC, Sarafa2n commented on source/format.js
> +    });
Давай переделаем это на `reduce`, можно будет избавиться от `result`

2021-08-30 09:14 UTC, Sarafa2n commented on source/format.js
> +    var result = "";
Давай не будем использовать `var`, это устаревшее объявление, давай использовать `let` или `const`

2021-08-30 09:14 UTC, Sarafa2n commented on source/format.js
> +    });
Давай переделаем на `reduce`

2021-08-30 14:16 UTC, a1i5k commented on source/format.js
> +'use strict';
Данная директива включает строгий режим обработки кода. Когда разработчик языка изменяет какие-либо функции (переделывает реализацию для оптимизации или исправляет найденные в ней ошибки), чтобы они работали по старому образцу, это директиву прописывать не нужно. При написанной директиве включается "современный" режим при котором изменяется логика относительно ошибок: будет выдаваться исключение, а не просто игнорироваться, что помогает быстрее найти ошибку; так же нельзя нельзя присваивать значение в неопределённую переменную (в неограниченном режиме создается глобальная переменная); становится больше слов, зарезервированных для использования в будущем, жёстко регулируется использование функции eval и объекта arguments

2021-08-30 14:33 UTC, Sarafa2n requested changes

2021-08-30 14:33 UTC, Sarafa2n commented on source/format.js
> +const format = function (numbers, col) {
Сорян, не дописал, нужно другим способом функцию объявить. (Стрелочную функцию сделай)

2021-08-30 14:33 UTC, Sarafa2n commented on source/format.js
> +  * @param {integer number} col - количество колонок
Кажется типы неправильные, посмотри вот тут https://jsdoc.app/tags-type.html

2021-08-30 14:33 UTC, Sarafa2n commented on source/format.js
> +    }
Это зачем?

2021-08-30 14:33 UTC, Sarafa2n commented on source/format.js
> +    });
у reduce есть `accumulator` https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce
можно обойтись без `slots`
Если не поймешь напиши мне в телеге @sarafa2n

2021-08-30 14:33 UTC, Sarafa2n commented on tests/format.js
> +	});
Можно объединить в один тест

2021-08-30 14:33 UTC, Sarafa2n commented on source/format.js
> +}
Тут тоже можно по-другому

2021-08-30 17:51 UTC, Sarafa2n requested changes

2021-08-30 17:51 UTC, Sarafa2n commented on source/format.js
> +    let slots = numbers.reduce(function(acc, currentValue, index) {
const

2021-08-30 17:51 UTC, Sarafa2n commented on source/format.js
> +            }
давай это заменим на условный оператор

2021-08-30 17:51 UTC, Sarafa2n commented on source/format.js
> +        const newAcc = acc + currentValue.toString().padStart(slots[index % col], " ");
можно передать просто число в `padStart`

2021-08-30 17:51 UTC, Sarafa2n commented on source/format.js
> +        if (index != numbers.length - 1) {
а почему не `!==`

2021-08-30 17:51 UTC, Sarafa2n commented on source/format.js
> +            if ((index + 1) % col == 0) {
почему не `===` ?

Вот тут почитай https://learn.javascript.ru/comparison

2021-08-30 17:51 UTC, Sarafa2n commented on source/format.js
> +        return null;
а давай не null возвращать, а выкидывать ошибку https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Error

2021-08-30 17:52 UTC, Sarafa2n commented on source/format.js
> +    let slots = numbers.reduce(function(acc, currentValue, index) {
`const`

2021-08-30 19:23 UTC, Sarafa2n requested changes

2021-08-30 19:23 UTC, Sarafa2n commented on source/format.js
> +            return newAcc;
а если заменить `newAcc` на `acc` ?

2021-08-30 19:23 UTC, Sarafa2n commented on source/format.js
> +            return newAcc + ((index + 1) % col === 0 ? '\n' : ' ');
наверно лучше вынести `((index + 1) % col === 0 ? '\n' : ' ')` в отдельную переменную

2021-08-30 20:13 UTC, Sarafa2n requested changes

2021-08-30 20:13 UTC, Sarafa2n commented on source/format.js
> +            acc[index % col] = currentValue.toString().length;
`index % col` тоже можно вынести в переменную

2021-08-30 20:13 UTC, Sarafa2n commented on source/format.js
> +       })) {
а посмотри что с скобками, кажется чет не то

2021-08-30 20:13 UTC, Sarafa2n commented on source/format.js
> +            if (typeof(element) == 'string')
`===`

2021-08-31 07:15 UTC, Sarafa2n requested changes

2021-08-31 07:15 UTC, Sarafa2n commented on source/format.js
> +    if (numbers.some(element => {
Тут зря ты убрал скобки, нужно было ниже расставить скобки правильно (23 строка)

2021-08-31 07:15 UTC, Sarafa2n commented on source/format.js
> +            acc[index % col] = currentValue.toString().length;
тут не поправил

2021-08-31 16:15 UTC, Sarafa2n requested changes

2021-08-31 16:15 UTC, Sarafa2n commented on source/format.js
> +        const indexCol = index % col
`;` пропала

2021-08-31 16:15 UTC, Sarafa2n commented on source/format.js
> +        if (currentValue.toString().length > acc[indexCol]) {
`acc[indexCol]` вынеси в отдельную переменную

2021-09-01 05:24 UTC, Sarafa2n requested changes

2021-09-01 05:24 UTC, Sarafa2n commented on source/format.js
> +            acc[indexCol] = currentValue.toString().length;
тут не исправил

2021-09-01 05:24 UTC, Sarafa2n commented on source/format.js
> +        const maxLenCheckingCol = acc[indexCol];
можно оставить `const maxLenCheckingCol = acc[index % col];`

2021-09-01 14:41 UTC, Sarafa2n requested changes

2021-09-01 14:41 UTC, Sarafa2n commented on source/format.js
> +
Зачем?

2021-09-01 14:41 UTC, Sarafa2n commented on source/format.js
> +
У функции нет JSDoc

2021-09-01 14:41 UTC, Sarafa2n commented on source/format.js
> +    if (numbers.some((element) => { return checkElementArray(element); })) {
тут можно просто () => check....

2021-09-01 14:50 UTC, Sarafa2n approved these changes

2021-09-01 21:53 UTC, Betchika99 requested changes

2021-09-01 21:53 UTC, Betchika99 commented on source/format.js
> + */
немного странный JSDoc. Приведи его к более корректному виду

2021-09-02 06:43 UTC, Sarafa2n requested changes

2021-09-02 06:43 UTC, Sarafa2n commented on source/format.js
> + */
У тебя внизу правильно написан JSDoc, сделай как там

2021-09-02 11:43 UTC, Sarafa2n requested changes

2021-09-02 11:43 UTC, Sarafa2n commented on source/format.js
> + * @param {Array} numbers - массив чисел, которые надо отформатировать
Типа такого нет https://jsdoc.app/tags-param.html

2021-09-02 11:58 UTC, Sarafa2n requested changes

2021-09-02 11:58 UTC, Sarafa2n commented on source/format.js
> + * @param {*} element - проверяемый элемент
А давай не `*`  https://jsdoc.app/tags-param.html

2021-09-02 17:20 UTC, Sarafa2n requested changes

2021-09-02 17:20 UTC, Sarafa2n commented on source/format.js
> + * @returns {string}
А что если на вход было передан объект, тип возвращаемый будет не строка

2021-09-02 17:20 UTC, Sarafa2n commented on source/format.js
> +        return element;
давай возвращать false или true

2021-09-02 17:58 UTC, Sarafa2n approved these changes

2021-09-02 19:22 UTC, closed without merging