Волынец Александра
frontend-park-mail-ru/homework_2021_2 pull request #24
Opened 2021-08-29 17:25 UTC by theantialex

2021-08-30 13:03 UTC, alexey-ershkov commented on source/rle.js
> +const rle = input => input.length ? input.match(/(.)\1*/g).map(elem =>  elem.length - 1 ? elem[0] + elem.length : elem[0]).join('') : '';
Нет переноса на новую строку в конце файла. Давай лучше явно напишем условие `elem.length === 1`, так будет в разы читаемее

2021-08-30 13:06 UTC, alexey-ershkov commented on tests/rle.js
> +	});
Давай добавим пак тестов, когда тебе на вход подаются не строки

2021-08-31 15:10 UTC, theantialex commented on source/rle.js
> +'use strict';
Эта директива указывает, что программа должна работать в строгом режиме. Он предотвращает некоторые небезопасные действия, ловит больше ошибок, вызывая исключения.

2021-08-31 15:13 UTC, alexey-ershkov commented on source/rle.js
> +'use strict';
Да, все верно)

2021-08-31 15:15 UTC, alexey-ershkov requested changes

2021-08-31 15:15 UTC, alexey-ershkov commented on source/rle.js
> +const rle = input => input.length ? input.match(/(.)\1*/g).map(elem =>  elem.length == 1 ? elem[0] : elem[0] + elem.length).join('') : '';
Лучше использовать строгое сравнение `elem.length === 1`

2021-08-31 15:15 UTC, alexey-ershkov commented on tests/rle.js
> +	QUnit.test('rle работает правильно при некорректном вводе', function (assert) {
А если ввести undefined или null?

2021-08-31 16:34 UTC, alexey-ershkov approved these changes

2021-09-02 09:08 UTC, alexey-ershkov requested changes
Привет) Нашел небольшую ошибку

2021-09-02 09:08 UTC, alexey-ershkov commented on source/rle.js
> +const rle = input => typeof input == 'string' && input.length ?
Почему используешь нестрогое сравнение? Подробнее можно почитать [здесь](https://learn.javascript.ru/comparison#strogoe-sravnenie)

2021-09-03 07:33 UTC, alexey-ershkov approved these changes

2021-09-03 08:28 UTC, closed without merging