Dudnik Maksim Variant 12
frontend-park-mail-ru/homework_2021_2 pull request #25
Opened 2021-08-29 17:43 UTC by maksongold

2021-08-30 08:07 UTC, Alkirys commented
Привет и добро пожаловать на 2 семестр Технопарка! Я буду проверять твое нулевое дз по фронтенду, так что в случае возникновения вопросов не стесняйся писать) Мой ник в телеге @Alkirys.

У меня есть несколько комментариев по коду, но в целом могу сказать, что ты отлично поработал. Отдельный респект за то, что разобрался с регулярками👍

2021-08-30 08:23 UTC, Alkirys commented on source/minmax.js
> +'use strict';
Круто, что ты используешь 'use strict', расскажи, почему ты решил, что он здесь нужен?

2021-08-30 08:23 UTC, Alkirys commented on source/minmax.js
> +const minmax = function (str) {
Как смотришь на то, чтобы использовать тут стрелочную функцию?)

2021-08-30 08:23 UTC, Alkirys commented on source/minmax.js
> +    if (numbsFromStr == null)
Расскажи, почему ты решил использовать в этом месте оператор ==, а не ===

2021-08-30 08:23 UTC, Alkirys commented on tests/minmax.js
> +	});
Подумай, какие еще случаи можно проверить. 
Дам подсказку: подумай про негативные тесты)

2021-08-30 08:23 UTC, Alkirys commented on source/minmax.js
> +        return [undefined, undefined]
Не забывай ставить ;

2021-08-30 08:23 UTC, Alkirys commented on source/minmax.js
> +const minmax = function (str) {
Давай добавим JSDoc, чтобы было сразу понятно, зачем нужна эта функция и с какими значениями она работает

2021-08-30 09:47 UTC, maksongold commented on source/minmax.js
> +    if (numbsFromStr == null)
потому что при нестрогом равенстве null равен undefined

2021-08-30 09:51 UTC, maksongold commented on source/minmax.js
> +const minmax = function (str) {
положительно

2021-08-30 09:55 UTC, maksongold commented on source/minmax.js
> +'use strict';
Здесь он в принципе не нужен, будет работать и без него, но как хорошая практика его лучше использовать, так как он ограничивает некоторые неприятные возможности, типа присваивания в неопределенную переменную (x=5)

2021-08-30 12:33 UTC, Alkirys commented on source/minmax.js
> +    if (numbsFromStr == null)
Метод match возвращает либо массив, либо null, кажется, здесь не нужно проверять на undefined

2021-08-30 12:33 UTC, Alkirys commented on source/minmax.js
> +    if (typeof(str) != "string")
В javascript предпочитается использование одинарных кавычкек)

2021-08-30 12:33 UTC, Alkirys commented on source/minmax.js
> +    if (typeof(str) != "string")
А тут почему !=

2021-08-30 12:35 UTC, Alkirys commented on source/minmax.js
> +const minmax = function (str) {
Отлично)

2021-09-02 07:57 UTC, Alkirys commented
Привет! Мне тут сказали, что нужно уделять больше внимания синтаксису и некоторым другим вещам, так что, у меня есть еще несколько замечаний по твоему коду

2021-09-02 08:01 UTC, Alkirys requested changes

2021-09-02 08:01 UTC, Alkirys commented on source/minmax.js
> +    if (numbsFromStr === null)
Здесь можно написать лаконичнее. В js null автоматически кастится к булевскому значению

2021-09-02 17:35 UTC, Alkirys requested changes

2021-09-02 17:35 UTC, Alkirys commented on source/minmax.js
> +            return [undefined, undefined];
Тут лучше будет обойтись без блока try-catch) потому что он тратит больше ресурсов, чем простая проверка условия

2021-09-03 00:05 UTC, Alkirys commented on source/minmax.js
> +const minmax = (str) => {
Давай назовем str более информативно

2021-09-03 00:05 UTC, Alkirys commented on source/minmax.js
> + * @return {Array} returns array in which the first elem is min numb, the second - max numb
Посмотри [тут](https://jsdoc.app/tags-param.html), как правильно обозначать массивы в JSDoc

2021-09-03 09:23 UTC, Alkirys commented on source/minmax.js
>          throw new Error('Incorrect input');
В js есть специальный [объект ошибки](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/TypeError), который применяется, когда аргумент, переданный в функцию, не совместим с ожидаемым типом

2021-09-03 17:40 UTC, Alkirys commented on tests/minmax.js
> +			},
Давай в этом и в следующих 2 тестах воспользуемся стрелочной функцией

2021-09-03 18:07 UTC, Alkirys approved these changes

2021-09-03 20:26 UTC, closed without merging