Винников Степан
frontend-park-mail-ru/homework_2021_2 pull request #27
Opened 2021-08-29 18:56 UTC by comradyo

2021-08-30 08:50 UTC, gavroman commented
Привет, добро пожаловать на курс по фронтенду! Сейчас проверим твое дз, если возникнут вопросы смело обращася в тг: @gavroman)

2021-08-30 08:53 UTC, gavroman commented on source/letters.js
> +const letters = function (str, condition) {
круто, что используешь function expression, расскажешь, чем отличается от function declaration?
1) Давай попробуем заиспользовать тут стрелочную функцию
2) Давай напишем [JSDoc комент](https://coderoad.ru/29333830/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B9-JSDoc-%D0%B2-%D0%BA%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-JSDoc) к этой функции

2021-08-30 08:53 UTC, gavroman commented on source/letters.js
> +    //return newStr;
лишних коментов быть не должно

2021-08-30 08:54 UTC, gavroman commented on source/letters.js
> +        let newStr = "";
в js принято использовать одинарные кавычки, предлагаю заменить

2021-08-30 08:58 UTC, gavroman commented on source/letters.js
> +            if (str.indexOf(str[i]) == str.lastIndexOf(str[i])) {
чем отличается `==` от `===`?  что лучше использовать?

2021-08-30 09:01 UTC, gavroman commented on source/letters.js
> +        var result = Array.from(new Set(str)).join('');
круто, что используешь Set! Какой еще есть способ превратить множество в массив?

2021-08-30 09:03 UTC, gavroman commented on source/letters.js
> +        return result.split("").reverse().join('')
1) чем var отличается от let и const? почему тут используешь var?

2021-08-30 09:11 UTC, gavroman commented on source/letters.js
> +        return str;
давай попробуем заюзать тут switch case

2021-08-30 09:13 UTC, gavroman commented on tests/letters.js
> +	QUnit.test('Ну... там... ещё что-то делает...', function (assert) {
1) давай напишем валидное название тесткейса с описанием проверок, которые в нем происходят
2) что произойдет, если в твою функцию вместо строки передадут массив/число/null/undefined, а вместо boolean в condition прилетит массив? Давай добавим проверок на входные данные и допишем тесты на эти случаи

2021-08-30 09:19 UTC, gavroman requested changes
давай исправлять/отвечать и получать апрув!)

2021-08-30 10:04 UTC, comradyo commented on source/letters.js
> +const letters = function (str, condition) {
Спасибо)
По сути, function expression - это подобие лямбда-функций в C++, мы присваиваем переменной типа "функция" значение типа "функция"

2021-08-30 11:15 UTC, comradyo commented on source/letters.js
> +            if (str.indexOf(str[i]) == str.lastIndexOf(str[i])) {
=== - это строгая эквивалентность - у сравниваемых величин должны быть равны как типы, так и значения.
== - это равенство, допускающее приведение типов.
В данном случае лучше использовать ===, поскольку в функцию вторым параметром передаются булевские переменные (true или false).
Если бы использовалось двойное равно, то числовая единица была бы эквивалентна true, что в строгом смысле не является верным.

2021-08-30 11:23 UTC, comradyo commented on source/letters.js
> +        var result = Array.from(new Set(str)).join('');
Можно сделать массив через spread syntax.
Пример:
let strSet = new Set(str);
var result = [...strSet].join('');

2021-08-30 12:32 UTC, gavroman commented on source/letters.js
> +            if (str.indexOf(str[i]) == str.lastIndexOf(str[i])) {
да, все верно, но есть негласное правило - везде юзать строгое равно/не равно, некоторые ide даже подсвечивают нестрогое равенство ворнингом

2021-08-30 12:42 UTC, gavroman commented
еще немного осталось)

2021-08-30 14:02 UTC, comradyo commented on source/letters.js
> +        return result.split("").reverse().join('')
Честно говоря, не очень разобрался, как работают let и const в else-if, поэтому пришлось использовать var, с ним всё работает.
========
2 раза заревёрсил для того, чтобы сначала перевернуть строку и сделать из неё множество (элементы будут добавляться в это множество с конца строки, таким образом выполнится условие для condition = false), и ещё раз произвожу реверс, чтобы получить отредактированную строку, записанную в правильном порядке.

2021-08-30 14:03 UTC, comradyo commented on tests/letters.js
> +	QUnit.test('Ну... там... ещё что-то делает...', function (assert) {
1. Исправил)
2. Сделал тесты на проверку этих случаев.

2021-08-30 14:03 UTC, comradyo commented on source/letters.js
> +            if (str.indexOf(str[i]) == str.lastIndexOf(str[i])) {
Пофиксил

2021-08-30 14:42 UTC, gavroman commented on source/letters.js
> +    {
скобочка уехала

2021-08-30 14:52 UTC, gavroman commented on tests/letters.js
> +	QUnit.test('Ну... там... ещё что-то делает...', function (assert) {
1) ок
2) Тестики конечно хорошо, только они не все покрывают. `letters({lol: 'kek', 2: 'чебурек'})`или `letters('нормальная строка', NaN)` что если так? Нужна честная проверка на тип данных (подсказка `typeof`). Что делать в случае невалидных данных - решать тебе)

2021-08-30 14:53 UTC, gavroman commented on source/letters.js
> +        return result.split("").reverse().join('')
2 и 3 - ок. А с let const и var давай разбираться. Подсказка - область видимости, блоки

2021-08-30 15:23 UTC, comradyo commented on source/letters.js
> +        return result.split("").reverse().join('')
Вроде разобрался:

var имеет или глобальную, или локальную область видимости, а const и let - блочную.

В случае с switch, let не работает, поскольку все case находятся в одной области видимости, поэтому возникает ошибка повторного объявления.

const - это, по сути, let, который уже нельзя переопределять.

2021-08-30 16:19 UTC, gavroman commented on source/letters.js
> +        return result.split("").reverse().join('')
отлично, а теперь давай сделаем на каждый case свою область видимости и заюзаем let/const вместо var, потому что var - устаревшая штука, вызывающая проблемы, о которых ты наверное уже почитал)

2021-08-30 21:36 UTC, comradyo commented on source/letters.js
> +        return result.split("").reverse().join('')
Всё, доделал

2021-08-31 06:07 UTC, gavroman commented on source/letters.js
> +                let strSet = new Set([...str].reverse().join(''));
почему `let`, а не `const`?

2021-08-31 06:07 UTC, gavroman commented on source/letters.js
> +            {
скобочка уехала

2021-08-31 08:44 UTC, comradyo commented on source/letters.js
> +                let strSet = new Set([...str].reverse().join(''));
По сути, здесь, наверное, логичнее использовать const, так как переменную не требуется менять позже.

2021-08-31 08:45 UTC, comradyo commented on source/letters.js
> +            {
Исправил

2021-08-31 10:12 UTC, gavroman approved these changes

2021-09-02 10:10 UTC, Betchika99 requested changes

2021-09-02 10:10 UTC, Betchika99 commented on source/letters.js
> +    if (typeof (str) != 'string' || (typeof (condition) != 'undefined' && typeof (condition) != 'boolean')) {
Корректнее использовать строгие сравнения, они проверяют типы переменных и позволяют не пропустить баги.

2021-09-02 10:10 UTC, Betchika99 commented on source/letters.js
> +    if (typeof (str) != 'string' || (typeof (condition) != 'undefined' && typeof (condition) != 'boolean')) {
Эта строка довольно длинная и тяжело читается, давай ее разобьем

2021-09-02 10:10 UTC, Betchika99 commented on source/letters.js
> +const letters = (str, condition) => {
Давай назовём str более информативно. А то внутри кода она выглядит как временная переменная

2021-09-02 10:10 UTC, Betchika99 commented on source/letters.js
> +        }
В этом кейсе лучше использовать для накопления результата перебирающий метод массивов reduce

2021-09-02 10:10 UTC, Betchika99 commented on source/letters.js
> +            for (let i = 0; i < str.length; ++i) {
А почему ++i? Ты хочешь сначала поднимать индекс, а потом проходить итерацию?

2021-09-02 17:02 UTC, comradyo commented on source/letters.js
> +        }
Исправил

2021-09-02 17:02 UTC, comradyo commented on source/letters.js
> +const letters = (str, condition) => {
Поправил

2021-09-03 08:02 UTC, comradyo commented on source/letters.js
> +    if (typeof (str) != 'string' || (typeof (condition) != 'undefined' && typeof (condition) != 'boolean')) {
Сделал

2021-09-03 08:02 UTC, comradyo commented on source/letters.js
> +    if (typeof (str) != 'string' || (typeof (condition) != 'undefined' && typeof (condition) != 'boolean')) {
Исправил

2021-09-03 11:19 UTC, closed without merging