Making variant 8
frontend-park-mail-ru/homework_2021_2 pull request #28
Opened 2021-08-29 21:17 UTC by MollenAR

Привет тому кто будет меня проверять!
Я Аристов Алексей из группы АПО-22

2021-08-30 12:04 UTC, Xatabch reviewed
Писать по вопросам можно в телегу (ник xatabch)

2021-08-30 12:04 UTC, Xatabch commented on source/sort.js
> +        lowerCaseWord = [...lowerCaseWord].sort( (a, b) => new Intl.Collator(['ru', 'jp']).compare(a, b) );
не совсем понимаю смысл в этой конструкции, .sort производит сортировку на месте, почитать об этом можно например тут https://en.wikipedia.org/wiki/In-place_algorithm тоесть можно не переприсваивать

2021-08-30 12:04 UTC, Xatabch commented on source/sort.js
> +    unSortedString.split(' ').forEach(word => {
а давай forEach переделаем на модный и классный метод .reduce, почитать о нем можно тут https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce

2021-08-30 23:55 UTC, MollenAR commented on source/sort.js
> +
будет кидать эксепшены TypeError, когда будет пытаться делать .split(' ')

2021-08-31 08:37 UTC, Xatabch commented on source/sort.js
> +
чтобы избежать подобных случаем, нужно добавить проверку, на то, что unSortedString не undefined, сделай это пожалуйста

2021-08-31 08:37 UTC, Xatabch commented on source/sort.js
> +
и напиши на это тесты

2021-08-31 08:37 UTC, Xatabch commented on index.html
>  <script src="source/max.js"></script>
удали так же сам файл max.js он не нужен

2021-08-31 08:41 UTC, Xatabch commented on source/sort.js
> +            .replace(/^./, symbolToCapitalise => symbolToCapitalise.toUpperCase());
зачем тут регулярка на обычный upperCase первой буквы, кажется это оверижиниринг + регулярки работают дольше, чем просто взять первый элемент из строки, давай исправим это

2021-08-31 08:43 UTC, Xatabch commented on source/sort.js
> +
тут стоит написать проверку, на то, что это не строка и докинуть на это тестов

2021-08-31 15:29 UTC, MollenAR commented on source/sort.js
> +        lowerCaseWord = [...lowerCaseWord].sort( (a, b) => new Intl.Collator(['ru', 'jp']).compare(a, b) );
если убрать присвоение то изменения не сохраняются, немного покопавшись понял почему:
я сортирую результат работы spread оператора, сама строка lowerCaseWord не изменилась, отсортировался только массив полученный spread оператором

2021-08-31 15:31 UTC, MollenAR commented on source/sort.js
> +        lowerCaseWord = [...lowerCaseWord].sort( (a, b) => new Intl.Collator(['ru', 'jp']).compare(a, b) );
и я там join('') добавил, он точно новую строку из массива собирает

2021-09-01 08:18 UTC, Xatabch commented on source/sort.js
> +        lowerCaseWord = [...lowerCaseWord].sort( (a, b) => new Intl.Collator(['ru', 'jp']).compare(a, b) );
ну, так в этом и суть что, если выполнить не [...lowerCaseWord].sort, а просто lowerCaseWord.sort(), тогда все изменится, spread оператором, ты копируешь текущий массив в массив [], поэтому ничего не изменялось

2021-09-03 11:05 UTC, Betchika99 requested changes

2021-09-03 11:05 UTC, Betchika99 commented on source/sort.js
> +let sort = unSortedString => {
почему здесь используется идентификатор let? у тебя будет как-то меняться функция? прочитай повнимательнее разницу между let/const/var

2021-09-03 11:05 UTC, Betchika99 commented on source/sort.js
> +let sort = unSortedString => {
по код стайлу параметры стрелочных функций лучше оборачивать в круглые скобки

2021-09-03 11:05 UTC, Betchika99 commented on source/sort.js
> +    if (typeof unSortedString != typeof String()) throw new TypeError('Incorrect type')
на строке 3 в JSDoc ты написал тип string, почему здесь ты проверяешь на инстанс String? ты же ожидаешь примитивную строку, должен быть просто string

2021-09-03 11:05 UTC, Betchika99 commented on source/sort.js
> +    let sortedString = unSortedString.split(' ').reduce( (sortedPart, word) => {
почему здесь тоже используется let?

2021-09-03 11:05 UTC, Betchika99 commented on source/sort.js
> +        lowerCaseWord = lowerCaseWord.replace(lowerCaseWord[0], symbolToCapitalise => symbolToCapitalise.toUpperCase());
эта строчка очень длинная, давай ее разобьем

2021-09-03 15:00 UTC, MollenAR commented on source/sort.js
> +    let sortedString = unSortedString.split(' ').reduce( (sortedPart, word) => {
тут тоже можно const, тк я не переприсваиваю sortedString, но если бы я по другому написал return пришлось бы использовать let

2021-09-03 15:00 UTC, MollenAR commented on source/sort.js
> +let sort = unSortedString => {
Поменял на const, тк функцию я переприсваивать не собираюсь, sort останется sort`ом

2021-09-03 20:28 UTC, closed without merging