Косенко Алексей Вариант 7
frontend-park-mail-ru/homework_2021_2 pull request #29
Opened 2021-08-30 02:13 UTC by saptded

2021-08-30 21:37 UTC, Howle-Great commented
Привет!) Поздравляю с переходом на второй семестр) Приветствую на курсе фронтенд разработки) Я один из менторов и буду проверять твое ДЗ. Будет интересный семестр) 

У тебя хорошее решение и правильно сделал, что нашёл функцию, которая нативно реализовывает раскрытие скобок. В JS много уже готовых функций.

Добавь, пожалуйста, JS-doc. А так у тебя очень хорошее решение =)

2021-08-30 21:38 UTC, Howle-Great commented on source/plain.js
> +'use strict';
Подскажи, пожалуйста, зачем тут нужна эта строчка?

2021-08-31 12:59 UTC, saptded commented on source/plain.js
> +'use strict';
Привет!
Если простыми словами, то она запрещает некоторые вольности языка ведущие к ошибкам, заменяет исключениями некоторые из них, в ряде случаев оптимизирует код.
чекал вот эти гайды↓↓↓
https://learn.javascript.ru/strict-mode
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Strict_mode
Решил написать так, потому что в книге по js была глава где советовали использовать эту директиву пока код не состоит из классов и модулей, хороший тон получается.
А так, конкретно в этом случае, эта строчка особо и не нужна)

2021-08-31 16:42 UTC, Howle-Great commented on source/plain.js
> +'use strict';
класс!

2021-08-31 16:45 UTC, Howle-Great commented
Немного поздно пишу, но давай сразу перепишем функцию flat на кастомную реализацию. Как я понял, все пришли к консенсусу, что слишком малой кровью делается этот вариант и так вы ничему не научитесь =)

П.С. Иногда такое задание 1 в 1 дают на собесах по js =P Это чтобы тебе не было так обидно...

2021-09-01 07:31 UTC, Howle-Great commented
Класс! Молодец! Для меня читабельно и нормально. Отдаю на проверку преподавателю

2021-09-01 21:34 UTC, Betchika99 requested changes

2021-09-01 21:34 UTC, Betchika99 commented on source/plain.js
> + * @returns {array} - массив элементов "поднятых" из всех подмассивов
в JSDoc [нет типа](https://jsdoc.app/tags-param.html) array

2021-09-01 21:34 UTC, Betchika99 commented on source/plain.js
> +const plain = array => {
по код стайлу параметры стрелочных функций лучше обрамлять круглыми скобками

2021-09-01 21:34 UTC, Betchika99 commented on source/plain.js
> +    return array.reduce((resultArray, currentElement) => resultArray.concat(Array.isArray(currentElement) ? plain(currentElement) : currentElement), []);
эта строчка очень длинная и плохо читаема. Перенеси ее, чтобы можно было хорошо понимать, где какая часть функций

2021-09-01 21:34 UTC, Betchika99 commented on source/plain.js
> +    return array.reduce((resultArray, currentElement) => resultArray.concat(Array.isArray(currentElement) ? plain(currentElement) : currentElement), []);
использовать рекурсию на клиенте - очень дорогая операция. Давай уберем ее

2021-09-03 11:18 UTC, closed without merging