Кожуро Борис Вариант 7
frontend-park-mail-ru/homework_2021_2 pull request #30
Opened 2021-08-30 12:57 UTC by BorisKoz

2021-08-30 20:41 UTC, Betchika99 requested changes
Привет! Добро пожаловать на курс фронтенда :) 
Ты сделал вполне хорошее решение, особенно мне понравился алгоритм. Но твой код больше похож на C++, чем на JavaScript, поэтому я дала довольно много рекомендаций на изучение именно этого языка. Тебе будет полезно освоить эти основы перед началом курса. 
Из общих замечаний - поправь еще code style по [этой статье](https://learn.javascript.ru/coding-style). 
Успехов 💪

2021-08-30 20:41 UTC, Betchika99 commented on source/chess.js
> +        boardStrings[0] += symbols[i%2]
конкатенировать символы и строки лучше с помощью шаблонных строк. Или хотя бы с помощью специальных методов строк. Почитай об этом [здесь](https://dev-gang.ru/article/-sposoba-obedinenija-strok-v-javascript-prgtacj4yl/)

2021-08-30 20:41 UTC, Betchika99 commented on tests/chess.js
> +        assert.strictEqual(chess('a'), null);
можно еще добавить проверку на передачу массива и/или объекта, а также null

2021-08-30 20:41 UTC, Betchika99 commented on tests/chess.js
> +        assert.strictEqual(chess('0'), null);
это проверка на строку, а не на ноль, лучше убрать/перенести в другой тесткейс

2021-08-31 05:25 UTC, BorisKoz commented on source/chess.js
> +'use strict';
Включение строгого режима для ES5

2021-08-31 05:26 UTC, BorisKoz commented
Изменил все по рекомендациям, или хотя бы попытался.

2021-08-31 11:05 UTC, Betchika99 requested changes
Уже гораздо лучше! Но есть, над чем еще поработать

2021-08-31 11:05 UTC, Betchika99 commented on source/chess.js
> +    }
т.к. ты здесь просто размножаешь строки, то можно попробовать использовать метод [repeat](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String/repeat), будет выглядеть симпатичнее

2021-08-31 11:05 UTC, Betchika99 commented on source/chess.js
> +        boardStrings[0] = `${boardStrings[0]}${symbols[(i%2)?'space':'star']}`;
давай сделаем выше переменную вида `const isEven = i%2;` и будем ее использовать ниже, так читаемее

2021-08-31 11:05 UTC, Betchika99 commented on tests/chess.js
> +    });
а почему это отдельные кейсы, а не случаи кейса "Ввод должен быть числом int"?

2021-08-31 18:01 UTC, BorisKoz commented on source/chess.js
> +    }
repeat не очень подходит, т.к. нужно чередовать 2 строки

2021-08-31 18:03 UTC, BorisKoz commented on source/chess.js
> +let chess = (boardSize) => {
чтобы назвать функцию chess

2021-08-31 18:06 UTC, BorisKoz commented on source/chess.js
> +    boardStrings = boardStrings.map(item => `${item}\n`);
если честно, не очень понимаю как это сделать

2021-08-31 18:07 UTC, BorisKoz commented on source/chess.js
> +        boardStrings[0] = `${boardStrings[0]}${symbols[(i%2)?'space':'star']}`;
сделал

2021-08-31 18:11 UTC, BorisKoz commented
null остается чтобы обеспечивать тест кейс

2021-08-31 18:14 UTC, BorisKoz commented
можно совет по поводу reduce? не оч понимаю как сделать

2021-08-31 19:19 UTC, Betchika99 commented
> можно совет по поводу reduce? не оч понимаю как сделать

конечно, пиши в телегу @emdobryanskaya

2021-08-31 19:22 UTC, Betchika99 commented on source/chess.js
> +let chess = (boardSize) => {
странный ответ. Название функции не отвечает за то, используешь ты let, var или const. Меня интересует выбор именно этого служебного слова: почему let? а теперь еще и var вообще

2021-08-31 19:23 UTC, Betchika99 commented
> null остается чтобы обеспечивать тест кейс

так ты же сам написал тест кейс, где проверяешь на null. Сделай более понятный возврат при невалидном инпуте и перепиши проверку в тестах. Делов-то :)

2021-09-02 09:39 UTC, closed without merging