Aleksandr Shibanov 6 variant
frontend-park-mail-ru/homework_2021_2 pull request #32
Opened 2021-08-30 13:51 UTC by AleksandrShibanov

Нужно было сделать елочку ;)

2021-08-30 16:18 UTC, Alkirys commented
Привет и добро пожаловать на 2 семестр Технопарка! Я буду проверять твое нулевое дз по фронтенду, так что в случае возникновения вопросов не стесняйся писать) Мой ник в телеге @Alkirys.

У меня есть несколько вопросов по коду, но могу сказать, что ты отлично поработал и найти какие-либо неточности было не просто👍

2021-08-30 16:24 UTC, Alkirys commented on source/tree.js
> +'use strict';
Круто, что ты используешь 'use strict', расскажи, почему ты решил, что он здесь нужен?

2021-08-30 16:24 UTC, Alkirys commented on source/tree.js
> +  }
А почему ты вынес эту проверку в отдельный if?)

2021-08-30 16:24 UTC, Alkirys commented on source/tree.js
> +  let res = "";
Тут ты используешь двойные кавычки, а во всех других местах - одинарные. Давай сделаем однообразно

2021-08-30 16:24 UTC, Alkirys commented on source/tree.js
> +function tree(height) {
Как смотришь на то, чтобы использовать тут стрелочную функцию?)

2021-08-30 16:24 UTC, Alkirys commented on tests/tree.js
> +	  assert.strictEqual(tree(null), null);
Подумай, какой еще негативный кейс можно проверить

2021-08-30 16:54 UTC, AleksandrShibanov commented on source/tree.js
> +'use strict';
Конкретно здесь он не нужен. Решил написать так, так как следовал этому гайду: https://learn.javascript.ru/strict-mode

2021-08-30 16:55 UTC, AleksandrShibanov commented on source/tree.js
> +  }
Разные по своей логике проверки. Одна проверка проверяет валидность поданного аргумента, другая - условие задачи

2021-08-30 16:56 UTC, AleksandrShibanov commented on source/tree.js
> +  let res = "";
Там где строка, использую двойные кавычки, там где символ - одинарные. Мне так удобнее

2021-08-30 16:58 UTC, AleksandrShibanov commented on source/tree.js
> +function tree(height) {
Функция довольно сложна для того, чтобы использовать стрелочную функцию. Не вижу смысла ее здесь внедрять, код получится не лаконичней, а наоборот запутанней.
А так да, стрелочные функции мне нравятся :)

2021-08-30 16:58 UTC, AleksandrShibanov commented on tests/tree.js
> +	  assert.strictEqual(tree(null), null);
Хорошо

2021-08-30 18:13 UTC, Alkirys commented on source/tree.js
> +function tree(height) {
Функция на самом деле не настолько большая, да и сам синтаксис стрелочных функций проще и лаконичнее. 
В общем случае, в javascript предпочтение отдается стрелочным функциям, кроме не которых случаев, когда могут возникнуть проблемы с определение контекста this(применение в методах объектов и функций с динамическим контекстом)

2021-08-30 18:16 UTC, Alkirys commented on source/tree.js
> +  let res = "";
В js считается хорошим тоном применение одинарных кавычек в коде, здесь нет такого четкого разделения на типы, как, например, в плюсах и символы также задаются с помощью одинарых кавычек)

2021-08-30 18:18 UTC, Alkirys commented on source/tree.js
> +  }
Да, такая логика вполне имеет место быть. Но в этом случае, стоить быть аккуратнее, чтобы в более сложных функциях не наплодить слишком много подобных проверок

2021-08-30 18:19 UTC, Alkirys commented on source/tree.js
> +'use strict';
Полностью согласен)

2021-08-31 16:42 UTC, Alkirys commented on source/tree.js
> +let tree = height => {
Напиши, почему ты решил использовать именно let?)

2021-08-31 16:51 UTC, AleksandrShibanov commented on source/tree.js
> +let tree = height => {
Согласен, лучше const

2021-09-02 08:03 UTC, Alkirys commented
Привет! Мне тут сказали, что нужно уделять больше внимания синтаксису и некоторым другим вещам, так что, у меня есть еще несколько замечаний по твоему коду

2021-09-02 08:05 UTC, Alkirys requested changes

2021-09-02 08:05 UTC, Alkirys commented on source/tree.js
> +const tree = height => {
По кодстайлу все параметры стрелочных функций лучше обрамлять круглыми скобками

2021-09-02 08:05 UTC, Alkirys commented on source/tree.js
> +  }
Давай все-таки объединим эти 2 условия в одно, так код будет выглядеть лаконичнее

2021-09-02 08:05 UTC, Alkirys commented on source/tree.js
> +  let res = '';
Давай переименуем переменную в result

2021-09-02 08:05 UTC, Alkirys commented on source/tree.js
> +    res += '\n';
Это сложение можно перенести на строчку выше

2021-09-02 08:24 UTC, Alkirys requested changes

2021-09-02 08:24 UTC, Alkirys commented on source/tree.js
> +    return null;
Будет лучше, если ты воспользуешься исключениями, чтобы сообщать пользователю об ошибке

2021-09-02 19:25 UTC, closed without merging