Variant 10 Лункин Владимир
frontend-park-mail-ru/homework_2021_2 pull request #34
Opened 2021-08-30 16:43 UTC by VladimirLunkin

2021-08-30 16:58 UTC, SPetrenko17 commented
Привет! Велком на второй сем технопарка. 
Решение рабочее, но совершенству нет предела)
У меня есть несколько вопросов по коду. Предлагаю отрефачить твое решение и докинуть еще тестов.

2021-08-30 17:00 UTC, SPetrenko17 commented on source/letters.js
> +function reverseString(str) {
Для начала предлагаю пробежаться по код-стайлу.
Рекомендую почитать про стрелочные функции и использовать их в твоем решении

2021-08-30 17:01 UTC, SPetrenko17 commented on source/letters.js
> +  return str.split("").reverse().join("");
Сейчас в JS коде предпочтительнее использовать одинарные кавычки

2021-08-30 17:08 UTC, SPetrenko17 commented on source/letters.js
> +  if (direction === false) str = reverseString(str);
Для читабельности кода лучше использовать фигурные скобки и переносы

2021-08-30 17:21 UTC, SPetrenko17 commented on source/letters.js
> +    if (str.indexOf(str[i], i + 1) == -1 || direction != undefined) {
Стоит разобраться с подводными камнями при сравнении в JS. Возможно, тут лучше использовать строгое сравнение

2021-08-30 17:26 UTC, SPetrenko17 commented on source/letters.js
> +  if (direction === false) str = reverseString(str);
Хорошая задумка с реверсом в начале и в конце. Для удобства можно заменить название второго пропса на reverse и не сравнивать его с false в начале и конце

2021-08-30 17:46 UTC, SPetrenko17 commented on source/letters.js
> +function reverseString(str) {
Кстати, также рекомендую использовать JSDoc в своих проектах. Это поможет лучше понимать свой код спустя долгое время)

2021-08-30 22:28 UTC, SPetrenko17 commented on tests/letters.js
> +	QUnit.test('Дополнительные тесты', function (assert) {
Думаю, лучше сгруппировать тесты и назвать их более конкретно. Как было в тест-кейсах выше

2021-08-30 22:39 UTC, SPetrenko17 commented on tests/letters.js
> +	QUnit.test('Дополнительные тесты', function (assert) {
+ Можно добавить тесты на те случаи, когда кидают мусор в мусор.  Добавить проверки в функции не помешало бы

2021-08-30 23:24 UTC, SPetrenko17 commented on tests/letters.js
> +		assert.throws(
Кажется, этого тут быть не должно

2021-09-03 11:11 UTC, Betchika99 requested changes

2021-09-03 11:11 UTC, Betchika99 commented on source/letters.js
> + * @param {String} str - Строка, которую нужно развернуть.
примитивные тип string и тип объекта String - это разные типы. Подумай, какой здесь верный.

2021-09-03 11:11 UTC, Betchika99 commented on source/letters.js
> + * @param {String} str - Строка, которую нужно развернуть.
str - не самое информативные название для переменной и очень схоже с примитивным типом. Давай поменяем это название

2021-09-03 11:11 UTC, Betchika99 commented on source/letters.js
> + * @return {String} - Новая строка без повторяющихся символов.
с типами тоже нужно разобраться и лишний раз не писать заглавную букву :)

2021-09-03 11:11 UTC, Betchika99 commented on source/letters.js
> +  if (typeof str !== 'string' && typeof(str) !== 'number') {
typeof обычно используется без скобочек

2021-09-03 11:11 UTC, Betchika99 commented on source/letters.js
> +  if (!(typeof direction === 'boolean' || typeof direction === 'undefined')) {
а если direction === null ?

2021-09-03 11:11 UTC, Betchika99 commented on source/letters.js
> +  }
почему здесь для накопления resultStr не использовать reduce?

2021-09-03 11:11 UTC, Betchika99 commented on source/letters.js
> +const letters = (str, direction) => {
аргумент типа true лучше называть как булевые переменные/функции с использованием is, например. Типа isEven, isNotGiven и тп

2021-09-03 11:11 UTC, Betchika99 commented on source/letters.js
> +    if (tempStr.indexOf(currSymbol, i) === -1 || direction !== undefined) {
для проверки наличия символа в строке можно использовать includes

2021-09-03 11:50 UTC, SPetrenko17 commented on source/letters.js
> +  if (!(typeof direction === 'boolean' || typeof direction === 'undefined')) {
Кажется, тут все корректно. direction Может передаться как boolean или вообще не передаваться. Намеренно передавать туда null не имеет смысла

2021-09-03 13:07 UTC, VladimirLunkin commented on source/letters.js
> +    if (tempStr.indexOf(currSymbol, i) === -1 || direction !== undefined) {
Метод includes проверяет наличие элемента в массиве, а у меня тут строка

2021-09-03 16:46 UTC, VladimirLunkin commented on source/letters.js
> +  }
Потому что исходная строка уменьшается, если встречаются повторяющиеся символы. Соответственно перебираем символы не так как в исходной строке.
Пример: строка "121" в цикле будет две итерации, в первой currSymbol=1, во второй currSymbol=2.
Как такое сделать с reduce я не смог придумать

2021-09-03 20:29 UTC, closed without merging