Пешков Дмитрий, АПО-21, вариант 17
frontend-park-mail-ru/homework_2021_2 pull request #35
Opened 2021-08-30 17:09 UTC by DPeshkoff

Добрый вечер!

- добавлена реализация _plainify.js_ + немного документации к ней;
- добавлено 4 новых теста: крупные примеры, большая степень вложенности, большое число повторов, символы из utf-8.

2021-08-30 17:44 UTC, Sarafa2n requested changes
Привет! Добро пожаловать на курс фронтенда! Я посмотрел твое решение, неплохое решение, но есть пару замечаний. Давай еще допишем тесты. Просто не понятно что будет если я вызову функцию например с массивом или со строкой.

2021-08-30 17:44 UTC, Sarafa2n commented on index.html
> +</html>
Этот файл не надо было трогать)

2021-08-30 17:44 UTC, Sarafa2n commented on tests/plainify.js
> +    QUnit.test('plainify нормально работает на большой степени вложенности (50)', function(assert) {
А Давай мы этот тест уберем.

У меня в экран не помещается весь объект

![image](https://user-images.githubusercontent.com/32399246/131379996-6a58532e-9000-4be6-b3ea-67580cecdc09.png)

2021-08-30 17:44 UTC, Sarafa2n commented on tests/plainify.js
> +});
Давай добавим пустую строку в конце файла. https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log

2021-08-30 17:44 UTC, Sarafa2n commented on source/plainify.js
> +}
Давай добавим пустую строку в конце файла. https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log

2021-08-30 17:44 UTC, Sarafa2n commented on source/plainify.js
> +    return result;
Давай переделаем это на `reduce`
И давай без использования `Object.assign()`

2021-08-30 17:44 UTC, Sarafa2n commented on source/plainify.js
> +'use strict'
А зачем это нужно?

2021-08-30 17:44 UTC, Sarafa2n commented on source/plainify.js
> +    let result = {};
это `const`

2021-08-30 22:44 UTC, DPeshkoff commented
Добрый ночи, исправил.

- _plainify.js_: переделано через `reduce`, `Object.assign()` убран;
- убран тест-лесенка;
- добавлены тесты строк и массивов;
- добавил пустые строки в конце файлов (IDE решила их поубирать мне зачем-то (аналогично с `index.html`, где она автоматически решила внести изменения);

2021-08-30 22:53 UTC, DPeshkoff commented on source/plainify.js
> +'use strict'
Конкретно здесь, если убрать, то ничего не сломается, но вообще это директива, заставляющая код обрабатываться в "строгом" режиме. Ввод директивы был необходим для обеспечения совместимости старого кода, который был написан до выхода ECMAScript 5, поэтому, как я понял, в новом коде желательно использование директивы (кроме того, это позволяет проще найти ошибки и защитить себя от использования опасных legacy-способов написания кода - в "строгом" режиме такое будет выбрасывать ошибку)

2021-08-31 07:09 UTC, Sarafa2n requested changes

2021-08-31 07:09 UTC, Sarafa2n commented on source/plainify.js
> +    const result = object_keys.reduce(function(result, key) {
А если мы сразу вернем? 
в reduce не `result` а `accumulator`

2021-08-31 07:09 UTC, Sarafa2n commented on source/plainify.js
> +    const object_keys = Object.keys(object);
А давай это уберем

2021-08-31 07:09 UTC, Sarafa2n commented on source/plainify.js
> +        const value = object[key];
Можно не `key` брать, а сразу ключ + значение посмотри методы объекта https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Object

2021-08-31 07:09 UTC, Sarafa2n commented on source/plainify.js
> +    }, {}, '');
кажется `''` лишняя

2021-08-31 07:09 UTC, Sarafa2n commented on source/plainify.js
> +        return result;
а давай подумаем как это можно превратить в две строки (используй условный оператор)

2021-08-31 07:09 UTC, Sarafa2n commented on tests/plainify.js
> +    QUnit.test('plainify работает правильно со строками', function(assert) {
![image](https://user-images.githubusercontent.com/32399246/131458608-c14e9fcc-f75c-46e9-8abf-7025286cc0cc.png)

Надо было чтобы если не объект на вход передан функция я бы выбрасывала ошибку

2021-08-31 12:09 UTC, DPeshkoff commented
Добрый день, исправил.

- _plainify.js_ переделан, берется ключ + значение, улучшена проверка определения нужных объектов;
- убраны лишние `''` ;
- `result `стал `accumulator `;
- `index.html` теперь должен был пофикситься;
- дописал еще тестов;

2021-08-31 12:11 UTC, DPeshkoff commented on tests/plainify.js
> -	});
Тест не удалялся, походу просто я где-то напортачил в коммитах, он все еще есть в коде и выполняется)

2021-08-31 12:13 UTC, Sarafa2n requested changes

2021-08-31 12:13 UTC, Sarafa2n commented on source/plainify.js
> +    if ((typeof object === 'object' && object !== null) && object.constructor !== undefined && (Object.getPrototypeOf(object) === Object.prototype || path !== '')) {
а давай  лучше лучше сделаем что-то вроде этого
`
if (typeof object !== 'object') {
   return ....
}
`

и вынесем проверку в отдельную функцию

2021-08-31 12:13 UTC, Sarafa2n commented on source/plainify.js
> +            const nested_object = typeof value !== 'object' ? {
`typeof value !== 'object'` я же писал что эта проверка не очень.

2021-08-31 12:13 UTC, Sarafa2n commented on source/plainify.js
> +            } : plainify(value, `${path}${key}.`);
давай сделаем по стайлгайдам

2021-08-31 13:53 UTC, DPeshkoff commented
Добрый день, исправил.

- проверка объекта заменена на обратную и вынесена в отдельную функцию;
- проверка объекта в теле поправлена;
- условный оператор поправлен по стайлгайду;
- небольшой фикс тестов;

2021-08-31 13:57 UTC, Sarafa2n requested changes

2021-08-31 13:57 UTC, Sarafa2n commented on source/plainify.js
> +///////////////////////////////////////////////////////////////////////////////
это что такое? 0_o

2021-08-31 13:57 UTC, Sarafa2n commented on source/plainify.js
> +    if (!isNotAnObject(object)) {
а давай мы сделаем вот так
![image](https://user-images.githubusercontent.com/32399246/131514914-0c1bdd85-6ad7-4e72-b26a-45c23da9910c.png)

2021-08-31 14:04 UTC, Sarafa2n requested changes

2021-08-31 14:04 UTC, Sarafa2n commented on tests/plainify.js
> -	});
давай это исправим

2021-08-31 16:20 UTC, DPeshkoff commented
Добрый день, исправил.

- заглушку убрал;
- `else` исправлен;
- тесты должны быть поправлены;

2021-08-31 16:24 UTC, Sarafa2n requested changes

2021-08-31 16:24 UTC, Sarafa2n commented on source/plainify.js
> +    if (!isNotAnObject(object)) {
так надо было так сделать 

`if (!isNotAnObject(object)) { return undefined}   return Object.entries.... `

2021-08-31 16:31 UTC, DPeshkoff commented
Добрый вечер, исправил.

- исправлен `if` в функции `plainify`;

2021-08-31 16:44 UTC, Sarafa2n requested changes

2021-08-31 16:44 UTC, Sarafa2n commented on source/plainify.js
> +    }
по хорошему это ошибка, давай сделаем через `throw` и `Error`

2021-08-31 17:35 UTC, DPeshkoff commented
Добрый вечер, исправил.

- ошибка теперь пишется в лог и выводится через `alert`.

2021-09-01 05:22 UTC, Sarafa2n requested changes

2021-09-01 05:22 UTC, Sarafa2n commented on source/plainify.js
> +	}
чет страшно, надо сделать также как было, но заменить `return undefined` на `throw ...`, а в тестах  `assert.throws()`

2021-09-01 07:45 UTC, DPeshkoff commented
Доброе утро, исправил.

- исправлены тесты под выброшенную ошибку.

2021-09-01 08:00 UTC, Sarafa2n requested changes

2021-09-01 08:00 UTC, Sarafa2n commented on source/plainify.js
> +            object.constructor === undefined ||
это можно заменить на просто `object` 
`null` и `undefined` в `if` выдает `false`

2021-09-01 08:00 UTC, Sarafa2n commented on tests/plainify.js
> +        	const _test_plainify_3_1 = {
Давай переделаем на `CamelCase` и можно не нумеровать)

2021-09-01 08:05 UTC, DPeshkoff commented on tests/plainify.js
> +        	const _test_plainify_3_1 = {
Без нумерации в тестах с несколькими assertions не получится, а в тестах в одним решил оставить для красоты)

2021-09-01 08:07 UTC, Sarafa2n commented on tests/plainify.js
> +        	const _test_plainify_3_1 = {
ну, лан, но CamelCase

2021-09-01 08:17 UTC, DPeshkoff commented
Доброе утро, исправил.

- исправлено условие в проверке объекта;

- названия переменных в тесте переписаны в `camelCase` (в вариант camelBack);

2021-09-01 08:35 UTC, Sarafa2n approved these changes

2021-09-01 21:58 UTC, closed without merging