Кучерявенко Алексей (вариант 9)
frontend-park-mail-ru/homework_2021_2 pull request #38
Opened 2021-08-31 08:27 UTC by frbgd

2021-08-31 08:48 UTC, Alkirys commented
Привет и добро пожаловать на 2 семестр Технопарка! Я буду проверять твое нулевое дз по фронтенду, так что в случае возникновения вопросов не стесняйся писать) Мой ник в телеге @Alkirys.

У меня есть несколько комментариев по коду, но в целом могу сказать, что ты отлично поработал. Отдельный респект за использование встроенных методов массивов и строк👍

2021-08-31 08:58 UTC, Alkirys commented on source/anagram.js
> +'use strict';
Круто, что ты используешь 'use strict', расскажи, почему ты решил, что он здесь нужен?

2021-08-31 08:58 UTC, Alkirys commented on source/anagram.js
> +function anagram(input) {
Как ты смотришь на то, чтобы использовать здесь стрелочную функцию?)

2021-08-31 08:58 UTC, Alkirys commented on source/anagram.js
> +    const normalized = input.map(function (word) {
Здесь и далее ты используешь ключевое слово function, но при этом не задаешь имя функции. В этом случае, использование стрелочной функции будет проще и лаконичнее)

2021-08-31 08:58 UTC, Alkirys commented on source/anagram.js
> +        map[item] = map[item] || [];
Мне кажется, тут лучше сделать проверку, нежели каждый раз переприсваивать значение

2021-08-31 08:58 UTC, Alkirys commented on tests/anagram.js
> +		assert.deepEqual(anagram(input), output);
Подумай, какие еще негативные тесты можно придумать)

2021-08-31 08:58 UTC, Alkirys commented on source/anagram.js
> +function anagram(input) {
Давай добавим JSDoc, чтобы было сразу понятно, зачем нужна эта функция и с какими значениями она работает

2021-09-01 07:50 UTC, frbgd commented on source/anagram.js
> +'use strict';
Для работы JS в стандарте >= ES5, в котором работает подавляющее большинство кода на JS. Так как код из файла anagram.js "не принадлежит" никакому классу и/или родительской функции, где было был объявлено 'use strict', его следует объявить в начале скрипта.

2021-09-01 07:57 UTC, frbgd commented on source/anagram.js
> +    const normalized = input.map(function (word) {
done

2021-09-01 08:06 UTC, frbgd commented on source/anagram.js
> +function anagram(input) {
done

2021-09-01 08:13 UTC, frbgd commented on source/anagram.js
> +        map[item] = map[item] || [];
done

2021-09-01 08:48 UTC, frbgd commented on tests/anagram.js
> +		assert.deepEqual(anagram(input), output);
done

2021-09-01 10:07 UTC, Alkirys commented on source/anagram.js
> + * @returns {*[[string]]} - list of anagrams
А что означает *? Никогда не видел такого обозначения, скинь ссылочку на стандарт пожалуйста)

2021-09-01 10:07 UTC, Alkirys commented on source/anagram.js
> +    const map = {};
Давай назовем переменную более осмысленно, потому что так как сейчас не очень понятно, для чего эта мапка нужна

2021-09-01 10:17 UTC, frbgd commented on source/anagram.js
> + * @returns {*[[string]]} - list of anagrams
Я ошибся в описании типа - правильно `string[][]`, `*[]` обозначает, что в списке могут быть объекты любого типа данных. Исправил

2021-09-01 10:24 UTC, frbgd commented on source/anagram.js
> +    const map = {};
done

2021-09-01 10:32 UTC, frbgd commented on source/anagram.js
> +'use strict';
- заменяет исключениями некоторые ошибки, которые интерпретатор JS ранее пропускал (создание и изменение глобальных переменных, удаление неудаляемых свойств, многоразовое перечисление свойств при инициализации object и аргументов при объявлении функций, и что-то еще есть, я обо всем не знаю);
- лучше оптимизирует выполнение кода;
- запрещает использовать некоторые ключевые слова (`implements, interface, let, package, private, protected, public, static, yield`)

2021-09-01 10:38 UTC, Alkirys commented on source/anagram.js
> +'use strict';
Отлично, все правильно

2021-09-01 21:40 UTC, Betchika99 requested changes

2021-09-01 21:40 UTC, Betchika99 commented on source/anagram.js
> +const anagram = input => {
по код стайлу все параметры стрелочных функций лучше обрамлять круглыми скобками

2021-09-01 21:40 UTC, Betchika99 commented on source/anagram.js
> +        return output;
а это валидный ответ? может лучше вернуть ошибку?

2021-09-01 21:40 UTC, Betchika99 commented on source/anagram.js
> +    if (!(Array.isArray(input) && input.every(item => typeof item === 'string')))
давай обернем блок этого ифа в фигурные скобки

2021-09-01 21:40 UTC, Betchika99 commented on source/anagram.js
> +    input.sort();
изменять исходные данные - плохая практика. Лучше, чтобы функция была чистой

2021-09-01 21:40 UTC, Betchika99 commented on source/anagram.js
> +    const normalized = input.map(word =>
не очень понятное название для переменной. Что лежит внутри? массив/мапа/строки, непонятно

2021-09-01 21:40 UTC, Betchika99 commented on source/anagram.js
> +            normalizedWordsMap[word] = [];
нужно обернуть в фигурные скобки

2021-09-01 21:40 UTC, Betchika99 commented on source/anagram.js
> +    const normalizedWordsMap = {};
а почему не использовать конструктор Map?

2021-09-01 21:40 UTC, Betchika99 commented on source/anagram.js
> +    });
это можно сделать с помощью перебирающего метода массивов reduce

2021-09-02 10:54 UTC, frbgd commented on source/anagram.js
> +const anagram = input => {
done

2021-09-02 10:55 UTC, frbgd commented on source/anagram.js
> +    if (!(Array.isArray(input) && input.every(item => typeof item === 'string')))
done

2021-09-02 10:56 UTC, frbgd commented on source/anagram.js
> +            normalizedWordsMap[word] = [];
done

2021-09-02 10:58 UTC, frbgd commented on source/anagram.js
> +        return output;
done

2021-09-02 10:59 UTC, frbgd commented on source/anagram.js
> +    const normalized = input.map(word =>
done

2021-09-02 11:04 UTC, frbgd commented on source/anagram.js
> +    input.sort();
done

2021-09-02 11:19 UTC, frbgd commented on source/anagram.js
> +    const normalizedWordsMap = {};
это все мой опыт на Python :)
done

2021-09-02 12:12 UTC, frbgd commented on source/anagram.js
> +    });
если честно, не понял, как это можно сделать через reduce, но немного оптимизировал по-другому, перенеся сортировку и инициализацию конечного списка в конец

2021-09-02 19:35 UTC, Alkirys requested changes

2021-09-02 19:35 UTC, Alkirys commented on source/anagram.js
> +    return [...normalizedWordsMap.values()].filter((item) => item.length > 1).map((item) => item.sort()).sort();
Проблема твоего решения в том, что ты 2 раза проходишься по массиву(сначала это делает filter, потом map). А с помощью reduce ты можешь получить искомый результат за один проход. 
Почитай эту [статью](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce), тут довольно хорошо описаны особенности метода и есть много примеров. Если будут вопросы - пиши в тг)

2021-09-02 19:35 UTC, Alkirys commented on source/anagram.js
> +        return null;
Думаю, будет лучше, если ты в данном случае будешь выкидывать исключение

2021-09-03 15:04 UTC, frbgd commented on source/anagram.js
> +        return null;
done

2021-09-03 15:15 UTC, frbgd commented on source/anagram.js
> +    return [...normalizedWordsMap.values()].filter((item) => item.length > 1).map((item) => item.sort()).sort();
done

2021-09-03 17:53 UTC, closed without merging

2021-09-03 18:18 UTC, Alkirys commented on source/anagram.js
> +    const normalizedWordsMap = input.slice().sort().reduce((map, word) => {
map - не говорящее название переменной

2021-09-03 18:18 UTC, Alkirys commented on tests/anagram.js
> +			() => { anagram(input); },
В случаях, когда в теле стрелочной функции нет вычислений и она просто что-то возвращает, фигурные скобки опускаются