Корчевский Александр
frontend-park-mail-ru/homework_2021_2 pull request #39
Opened 2021-08-31 11:32 UTC by just4n4cc

2021-09-01 00:20 UTC, yletamitlu reviewed
Приветствую на курсе фронтенда, хорошее решение дз0! Я оставила несколько комментов, поправь их пожалуйста)

2021-09-01 00:20 UTC, yletamitlu commented on source/tree.js
> +    const num = Number(number);
Если тут привести к числу с помощью унарного оператора '+', то условие в if может быть короче (потому что дробное число приведется к нулю, а ноль меньше трех)

2021-09-01 00:20 UTC, yletamitlu commented on source/tree.js
> +    const max_num = num * 2 - 3;
snak_case это конечно хорошо, но давай тут будем придерживаться camelCase)

2021-09-01 00:20 UTC, yletamitlu commented on source/tree.js
> +const tree = number => {
Добавь пожалуйста JSDoc к функциям https://ru.wikipedia.org/wiki/JSDoc

2021-09-01 00:20 UTC, yletamitlu commented on source/tree.js
> +        res += ' '.repeat(spaces_num) + '*'.repeat(asterisk_num) + ' '.repeat(spaces_num) + '\n';
Тут есть повторение
Что если придумать здесь что-то с 
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String/padEnd
и 
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String/padStart ?

Тогда можно будет вынести это в отдельную функцию, и воспользоваться ей же ниже, когда приделываем ёлке палку

2021-09-01 16:54 UTC, just4n4cc commented on source/tree.js
> +    const num = Number(number);
Прочитал, что унарный плюс это то же самое, что и Number(), к нулю дробное число не приводит(
Но запись стала короче, спасибо.

2021-09-01 16:58 UTC, just4n4cc commented
> Приветствую на курсе фронтенда, хорошее решение дз0! Я оставила несколько комментов, поправь их пожалуйста)

Привет, спасибо!

2021-09-01 21:29 UTC, yletamitlu commented on source/tree.js
> +    const num = Number(number);
Да, так точно, я что-то перепутала, извини! :) Ну зато знаешь теперь еще способ)

2021-09-01 21:37 UTC, yletamitlu reviewed
Суперски!

2021-09-01 22:01 UTC, Betchika99 requested changes

2021-09-01 22:01 UTC, Betchika99 commented on source/tree.js
> +    return res;
вместо фор здесь очень хорошо подойдет перебирающий метод массива reduce. Попробуй его применить :)

2021-09-02 15:42 UTC, just4n4cc commented on source/tree.js
> +    return res;
Поправил!

2021-09-02 16:19 UTC, closed without merging