Беляев Леонид
frontend-park-mail-ru/homework_2021_2 pull request #4
Opened 2021-08-25 15:26 UTC by 23-yo-designer-from-san-francisco

2021-08-28 09:38 UTC, Sarafa2n requested changes
Привет! Поздравляю тебя с переходом на второй семестр и добро пожаловать на курс фронтенда! Я отписал некоторые комментарии к решению. В целом кажется что можно упростить решение, если не поймешь как пиши, подскажу. Еще давай напишем больше тестов. Что будет если к примеру будет "Пила" и "липа"

2021-08-28 09:38 UTC, Sarafa2n commented on source/anagram.js
> +    var result = []
Давай не будем использовать var https://learn.javascript.ru/variables
В данном случае можно использовать const

2021-08-28 09:38 UTC, Sarafa2n commented on source/anagram.js
> +    for (var key in buckets) {
Давай уберем var, и можно использовать forEach

2021-08-28 09:38 UTC, Sarafa2n commented on source/anagram.js
> +            let intArray = [];
Тут можно использовать const

2021-08-28 09:38 UTC, Sarafa2n commented on source/anagram.js
> +            buckets[key].forEach(e => intArray.push(input[e[0]]));
Давай писать в одном стиле, Добавь скобки вокруг e

2021-08-28 09:38 UTC, Sarafa2n commented on source/anagram.js
> +    let buckets = input.map((e, i) => e = [i, e.split('').sort().join('')])
Тут можно использовать const
Давай обернем e в скобки
Давай вынесем `e.split('').sort().join('')` в отдельную переменную

2021-08-28 09:38 UTC, Sarafa2n commented on source/anagram.js
> +        .sort((e1, e2) => e1[1] > e2[1] ? -1 : 1)
Давай будет писать человекопонятные переменные

2021-08-30 17:12 UTC, Sarafa2n requested changes

2021-08-30 17:12 UTC, Sarafa2n commented on source/anagram.js
> +    });
давай это переделаем на `reduce`, и пожалуйста не `e` а `char` `symbol` ну или как нибудь иначе

2021-08-30 17:12 UTC, Sarafa2n commented on source/anagram.js
> +    }
тут тоже можно `reduce` использовать)

2021-08-30 17:12 UTC, Sarafa2n commented on tests/anagram.js
> +		];
давай уберем лишнюю строку

2021-08-31 07:11 UTC, Sarafa2n requested changes

2021-08-31 07:11 UTC, Sarafa2n commented on source/anagram.js
> +    const result = Object.entries(map).reduce((result, elem, index) => {
`reduce((result, elem, index)` `reduce((acc, elem, index)`

2021-08-31 09:26 UTC, Sarafa2n requested changes

2021-08-31 09:26 UTC, Sarafa2n commented on tests/anagram.js
> +	QUnit.test('Функция работает правильно [2]', function (assert) {
Давай напишем правильно с такими-то данными

2021-08-31 09:26 UTC, Sarafa2n commented on source/anagram.js
> +        if (elem[1]['length'] > 1) {
можно `.length`

2021-08-31 12:16 UTC, Sarafa2n requested changes

2021-08-31 12:16 UTC, Sarafa2n commented on source/anagram.js
> +    const map = input.sort().reduce((map, str, index) => {
`index` не используется

2021-08-31 12:16 UTC, Sarafa2n commented on source/anagram.js
> +        return acc;
Наверно логичнее использовать `Object.values()`

2021-08-31 12:27 UTC, Sarafa2n requested changes
Что будет если передан не массив? Давай добавим проверку, и тесты на это

2021-08-31 14:02 UTC, Sarafa2n requested changes

2021-08-31 14:02 UTC, Sarafa2n commented on source/anagram.js
> +            acc.push(value)
`;` пропала

2021-08-31 14:02 UTC, Sarafa2n commented on source/anagram.js
> +        throw 'Input is not an array';
Для ошибок есть специальный класс `Error`

2021-08-31 16:31 UTC, Sarafa2n approved these changes

2021-09-01 22:32 UTC, Betchika99 requested changes

2021-09-01 22:32 UTC, Betchika99 commented on source/anagram.js
> +function anagram(input) {
почему не использовать здесь стрелочную функцию?

2021-09-01 22:32 UTC, Betchika99 commented on source/anagram.js
> +    const map = input.sort().reduce((map, str) => {
sort изменяет исходный массив. Получается, что ты меняешь исходные данные и функция не будет чистой. Лучше использовать чистую функцию, которая не меняет приходящие в нее параметры.

2021-09-01 22:32 UTC, Betchika99 commented on source/anagram.js
> +}
переменные в этом файле не очень информативные. Лучше переименовать их более осмысленно

2021-09-02 07:35 UTC, Sarafa2n approved these changes

2021-09-02 08:22 UTC, Sarafa2n requested changes

2021-09-02 08:22 UTC, Sarafa2n commented on source/anagram.js
> + * @returns {Array} Array of anagrams in alphanumerical order
Типа Array нет https://jsdoc.app/tags-param.html

2021-09-02 08:30 UTC, closed without merging