Variant 5 chernyh nikita
frontend-park-mail-ru/homework_2021_2 pull request #43
Opened 2021-08-31 18:32 UTC by znjuko

2021-08-31 20:05 UTC, alexey-ershkov requested changes
Приветствую на курсе фронтенд разработки) Поздравляю с переходом на второй семестр! Крутое решение) Давай приведем в порядок файлики и сделаем пару небольших правок)

2021-08-31 20:05 UTC, alexey-ershkov commented on source/chess.js
> +            board += (i + j) % 2 === 0 ? '*' : ' ';
кажется можно упростить условие
`(i + j) % 2 ? '  ' : '*'`

2021-09-01 14:12 UTC, znjuko commented on source/chess.js
> +let chess = (size) => {
поменял на const. 
понимаю, что const стоит объявлять объекты/функции, чтобы ограничить возможность переприсваивания.

но в данном случае это не играет какой-либо весомой роли по причине проекта одной функции:)

2021-09-01 14:23 UTC, znjuko commented on source/chess.js
> +"use strict";
данный режим позволяет быстро находить некоторые ошибки (например, невозможность реализовывать функции с повторяющимися параметрами а-ля function(a,a)),  уведомляет об (ранее игнорируемых) ошибках (а-ля инициализация переменной без объявления и etc)

если подытожить: позволяет заранее предупредить разработчика о допущенных им ошибках/ обезопасить кодовую базу от помарок

2021-09-01 16:09 UTC, alexey-ershkov approved these changes

2021-09-02 09:20 UTC, alexey-ershkov requested changes
Привет) Дописал небольшую правку

2021-09-02 09:20 UTC, alexey-ershkov commented on tests/chess.js
> +
Нет негативных тестов для входных данных - давай их допишем

2021-09-02 09:24 UTC, alexey-ershkov approved these changes

2021-09-02 09:33 UTC, Betchika99 requested changes

2021-09-02 09:33 UTC, Betchika99 commented on source/chess.js
> +    if (!(size >= 2 && Number.isInteger(+size))) {
А почему 1 это невалидный размер? Из одной звездочки например

2021-09-02 09:33 UTC, Betchika99 commented on source/chess.js
> +const chess = size => {
По код стайлу лучше параметры стрелочных функций оборачивать в круглые скобки

2021-09-02 09:33 UTC, Betchika99 commented on tests/chess.js
> +    QUnit.test('Шахматная доска 5 на 5', function (assert) {
А зачем нужны тесты на 4 и 5? Чем они отличаются от тесты на 2 и 3? В чем информативность?

2021-09-02 10:40 UTC, znjuko commented on source/chess.js
> +    if (!(size >= 2 && Number.isInteger(+size))) {
Изначально, в дефолтных тестах, было указано такое поведение. 
Что в принципе логично - на доске размером 1x1 ты не сможешь разместить одновременную черную и белую фигуры

2021-09-02 10:40 UTC, znjuko commented on tests/chess.js
> +    QUnit.test('Шахматная доска 5 на 5', function (assert) {
Было добавлено просто для массы'

2021-09-02 10:40 UTC, znjuko commented on source/chess.js
> +const chess = size => {
fixed!

2021-09-03 08:30 UTC, closed without merging