Орлецкий Александр, АПО-22, вариант 4
frontend-park-mail-ru/homework_2021_2 pull request #45
Opened 2021-08-31 20:44 UTC by Trollbump

Добрый вечер!

- Добавлена реализация inverse.js и немного документации к ней
- Добавлены новые тесты: большие значения второго аргумента и массивы с одинаковыми элементами

2021-08-31 22:05 UTC, Slava-Romanov requested changes
Привет! Добро пожаловать на курс по фронтенду :) Сейчас я буду проверять твое нулевое дз. Если возникнут вопросы, не стесняйся, пиши в тг: @Slava_Romanov

2021-08-31 22:05 UTC, Slava-Romanov commented on source/inverse.js
> +'use strict';
Можешь рассказать для чего нужна эта строка?)

2021-08-31 23:08 UTC, Trollbump commented on source/inverse.js
> +    if (!(Array.isArray(arr))) { // return undefined if array is not array
Убрал

2021-08-31 23:08 UTC, Trollbump commented on source/inverse.js
> +    let arr_cp = arr.slice(); // make copy of array not to change anything in source
поменял на const

2021-08-31 23:08 UTC, Trollbump commented on source/inverse.js
> +/**
:3

2021-08-31 23:08 UTC, Trollbump commented on source/inverse.js
> + * @returns {Array|null}
Добавил пояснение в @returns

2021-08-31 23:09 UTC, Trollbump commented on source/inverse.js
> +const inverse = (arr, num = 0) => {
Добавил проверку второго аргумента на тип

2021-08-31 23:09 UTC, Trollbump commented on source/inverse.js
> +}
Добавил точку с запятой

2021-08-31 23:10 UTC, Trollbump commented on source/inverse.js
> +        let arr_reversed = arr_cp.splice(0, arr_cp.length + num);
Добавил дополнительную проверку для num = 0, теперь будет работать быстрее в таком случае

2021-08-31 23:10 UTC, Trollbump commented on source/inverse.js
> +        let arr_reversed = arr_cp.splice(0, arr_cp.length + num);
Поменял на const

2021-08-31 23:10 UTC, Trollbump commented on source/inverse.js
> +    else {
Объединил

2021-08-31 23:11 UTC, Trollbump commented on tests/inverse.js
> +
Добавил тесты на некорректные аргументы и корректную работу при вариативности наличия второго аргумента

2021-08-31 23:15 UTC, Trollbump commented on source/inverse.js
> +'use strict';
Ввод директивы был необходим для обеспечения совместимости старого кода, который был написан до выхода ECMAScript 5, поэтому, как я понял, в новом коде желательно использование директивы.
Еще это позволяет проще находить некоторые ошибки и защитить себя от использования опасных старых способов написания кода (поддержка которых осталась для обратной совместимости) - в "строгом" режиме такое будет выбрасывать ошибку

2021-09-01 16:29 UTC, Slava-Romanov requested changes

2021-09-01 16:29 UTC, Slava-Romanov commented on source/inverse.js
> +    const arr_cp = arr.slice();
Хорошая идея сделать копию массива, но кажется лучше здесь использовать Spread оператор

2021-09-01 16:29 UTC, Slava-Romanov commented on source/inverse.js
> +        return arr_cp.reverse();
Это можно вынести в самый низ, как случай, который произойдет, если не сработают > 0 и < 0

2021-09-01 17:26 UTC, Trollbump commented on source/inverse.js
> +        return arr_cp.reverse();
Поправил

2021-09-01 17:26 UTC, Trollbump commented on source/inverse.js
> +    const arr_cp = arr.slice();
заменил копирование с помощью slice на копирование с помощью spread-оператора

2021-09-01 18:16 UTC, Slava-Romanov approved these changes

2021-09-03 11:13 UTC, Betchika99 requested changes

2021-09-03 11:13 UTC, Betchika99 commented on index.html
> +<!-- <script src="tests/max.js"></script> -->
комменты убираем

2021-09-03 11:13 UTC, Betchika99 commented on source/inverse.js
> +    const arr_cp = [...arr];
в джс предпочтительнее использовать camelCase для переменных

2021-09-03 11:13 UTC, Betchika99 commented on source/inverse.js
> +        } else {
здесь не нужен else, т.к. в негативном случае интерпретатор все равно пойдет дальше и доберется до строки 21

2021-09-03 14:50 UTC, Trollbump commented on index.html
> +<!-- <script src="tests/max.js"></script> -->
убрал комменты

2021-09-03 14:51 UTC, Trollbump commented on source/inverse.js
> +    const arr_cp = [...arr];
поменял стиль именования переменных на camelCase

2021-09-03 14:51 UTC, Trollbump commented on source/inverse.js
> +        } else {
убрал "лишний" else

2021-09-03 20:30 UTC, closed without merging