Любский Юрий, вариант 11
frontend-park-mail-ru/homework_2021_2 pull request #46
Opened 2021-08-31 21:29 UTC by yurij-lyubskij

Новый реквест, на старый неназначался ментор

2021-09-01 06:06 UTC, gavroman commented
Привет, добро пожаловать на курс по фронтенду! Пока я буду проверять твое дз, допиши плиз в описание мра имя, фамилию и группу. Если возникнут вопросы, смело пиши в телегу @gavroman

2021-09-01 06:08 UTC, gavroman commented on source/rle.js
> +'use strict';
расскажи что это и для чего нужно?

2021-09-01 06:10 UTC, gavroman commented on source/rle.js
> +function rle(string)
давай попробуем заюзать стрелочную функцию, а еще напишем [JSDoc коментарий](https://coderoad.ru/29333830/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B9-JSDoc-%D0%B2-%D0%BA%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-JSDoc)

2021-09-01 06:10 UTC, gavroman commented on source/rle.js
> +{
скобочка уехала

2021-09-01 06:23 UTC, gavroman commented on source/rle.js
> +  return string.replace(/(.)\1+/g, function(a, b) {return b + a.length});
Очень крутое решение, но слишком простое).  Давай переименуем эту функу в `rleRegExp` и напишем еще 1 функу `rle` без регулярок, а по этой есть пара замечаний:
1) что если вместо строки в твою функу передать объект/массив/число/null/undefined?
2) кто такие `a` и `b`? го назовем их понятно
3) давай тут тоже заюзаем стрелочную функцию

2021-09-01 06:24 UTC, gavroman commented on tests/rle.js
> +﻿'use strict';
а что тут изменилось?

2021-09-01 06:26 UTC, gavroman commented on tests/rle.js
> +            assert.strictEqual(rle('BABB333'), 'BAB233');
понаехало

2021-09-01 09:58 UTC, yurij-lyubskij commented on source/rle.js
> +'use strict';
Это установка для включения "строгого режима". Это более безопасный режим, в котором отлавливаются "тихие" ошибки, которые в обычном режиме просто игнорируются, и запрещены некоторые опасные действия.

2021-09-01 10:13 UTC, yurij-lyubskij commented on tests/rle.js
> +﻿'use strict';
ничего)

2021-09-01 12:10 UTC, yurij-lyubskij commented
Исправил

2021-09-01 12:28 UTC, gavroman commented on source/rle.js
> +    :string.replace(/(.)\1+/g, (series, char) => (char + series.length));
давай лучше так перенесем
```suggestion
    condition 
       ? a
       : b
```

2021-09-01 12:28 UTC, gavroman commented on source/rle.js
> +    let rep_count = 0;
в js принято использовать camelCase

2021-09-01 12:29 UTC, gavroman commented on source/rle.js
> +        if (string[i] == string[i+1]) {
чем `==` отличается от `===`? что лучше юзать?

2021-09-01 12:46 UTC, yurij-lyubskij commented on source/rle.js
> +        if (string[i] == string[i+1]) {
=== проверяет на идентичность, а не равенство, не приводя к 1 типу, поэтому лучше использовать ===.

2021-09-01 13:27 UTC, gavroman commented on source/rle.js
> +    :string.replace(/(.)\1+/g, (series, char) => (char + series.length));
пробел после `:` потерялся, и, раз все равно править, давай еще отступы добавим перед ? и :

2021-09-01 13:28 UTC, gavroman commented on source/rle.js
> +    (typeof string != 'string')
давай тут тоже заюзаем строгое сравнение

2021-09-01 15:25 UTC, gavroman commented on tests/rle.js
> +
это все еще актуально

2021-09-01 15:43 UTC, yurij-lyubskij commented on tests/rle.js
> +
Исправил, вроде

2021-09-01 16:33 UTC, gavroman approved these changes

2021-09-03 10:58 UTC, Betchika99 requested changes

2021-09-03 10:58 UTC, Betchika99 commented on source/rle.js
> +const rleRegExp = (string) =>
название входной строки лучше сделать более информтивным. А то оно совпадает с типом вообще

2021-09-03 10:58 UTC, Betchika99 commented on source/rle.js
> +const rle = (string) => {
здесь тоже название переменной лучше поменять

2021-09-03 10:58 UTC, Betchika99 commented on source/rle.js
> +        return '';
а почему пустая строка, а не ошибка?

2021-09-03 10:58 UTC, Betchika99 commented on source/rle.js
> +    return compressed;
почему бы здесь для накопления compressed не использовать перебирающий метод массивов reduce?

2021-09-04 10:30 UTC, yurij-lyubskij commented on source/rle.js
> +const rleRegExp = (string) =>
переименовал в inputStr

2021-09-04 10:30 UTC, yurij-lyubskij commented on source/rle.js
> +const rle = (string) => {
сделал

2021-09-04 10:32 UTC, yurij-lyubskij commented on source/rle.js
> +        return '';
Теперь возвращаю объект ошибки.

2021-09-04 10:58 UTC, yurij-lyubskij commented on source/rle.js
> +    return compressed;
Потому что есть еще счетчик repCount, который несколько раз за цикл обнуляется. Его можно было бы хранить, как часть накапливаемой строки, но тогда на каждом шаге пришлось бы переводить его из символа в число и обратно.

2021-09-04 11:51 UTC, yurij-lyubskij commented on source/rle.js
> +    return compressed;
Сделал reduce

2021-09-04 12:04 UTC, closed without merging