Никитина Ксения. Вариант 13
frontend-park-mail-ru/homework_2021_2 pull request #47
Opened 2021-09-01 09:40 UTC by zdesbilaksenia

2021-09-01 13:50 UTC, lerakrya8 reviewed
Привет, Ксения!! Добро пожаловать на замечательный курс Фронтенд разработки и поздравляю с переходом на второй семестр!! Я буду проверять твое домашнее задание :) У тебя классной решение, но его можно чуточку улучшить. Буду ждать твоих исправлений!

Как исправишь, тегни меня тут или напиши и тг @lerakrya,  чтобы я могла как можно скорее тебе отписать :)

2021-09-01 13:50 UTC, lerakrya8 commented on source/get.js
> +        if (listOfProperties[i] !== '') {
это строчку можно сократить (условные операторы умеют конвертировать к булевскому значению). подробнее о значениях, которые конвертируются к true/false можно почитать тут https://www.samanthaming.com/tidbits/25-js-essentials-falsy-values/

2021-09-01 13:50 UTC, lerakrya8 commented on source/get.js
> +    for (let i = 0; i < listOfProperties.length; i++) {
проход по массиву можно реализовать с помощью его методов) почитать об этом можно тут https://learn.javascript.ru/array-methods

2021-09-01 14:33 UTC, zdesbilaksenia commented on source/get.js
> +'use strict';
use strict не дает использовать возможности старого стандарта языка, которые делали код менее понятным

2021-09-01 14:50 UTC, lerakrya8 commented on source/get.js
> +            if (object !== undefined)
вот эти 2 if можно объединить в один и уйдет лишняя вложенность)

2021-09-01 14:50 UTC, lerakrya8 commented on source/get.js
> +'use strict';
давай добавим JSDoc, чтобы сразу можно было понять, что это за функция, что принимает, что возвращает

2021-09-03 11:15 UTC, Betchika99 requested changes

2021-09-03 11:15 UTC, Betchika99 commented on source/get.js
> +const get = (object, properties) => {
переменная object не особо информативна + схожа с названием типа в джс. Давай поменяем ей название

2021-09-03 11:15 UTC, Betchika99 commented on source/get.js
> +    if (typeof object !== 'object' || typeof properties !== 'string')
null - это тоже object. Первая часть условия некорректна

2021-09-03 11:15 UTC, Betchika99 commented on source/get.js
> +            object = object[item];
изменять исходный параметр - это плохой тон. Все функции должны быть чистыми, т.е. не менять переданные в них параметры

2021-09-03 20:31 UTC, closed without merging