Перлин Леонид
frontend-park-mail-ru/homework_2021_2 pull request #49
Opened 2021-09-02 00:59 UTC by perlinleo

### **_Вариант №6_**

> **_Группа АПО-22_**

2021-09-02 22:57 UTC, zelflod requested changes
Йоу, приветствую на курсе! 

Оставил несколько замечаний, поправь плиз и снова отдай на ревью

2021-09-02 22:57 UTC, zelflod commented on index.html
>  <script src="tests/max.js"></script>
можно убрать файлы из примера

2021-09-02 22:57 UTC, zelflod commented on source/tree.js
> +    if (height < 3 || (!Number.isInteger(height)) || isNaN(height)) {
нет смысла оборачивать `!Number.isInteger(height)` в скобки

2021-09-02 22:57 UTC, zelflod commented on source/tree.js
> +    let res = '';
можно дать более понятное название

2021-09-02 22:57 UTC, zelflod commented on source/tree.js
> +        res += `${('*'.repeat(asteriskAmount)).padStart((maxWidth+asteriskAmount) / 2, ' ').padEnd(maxWidth)}\n`;
строка получилась слишком длинной, можно укоротить так
```
string.action()
       .secondAction()
       ...
```

выведи "*" в константы модуля (вне функции, в начало файла), чтобы не создавать каждый раз

не смысла оборачивать в скобки `'*'.repeat(asteriskAmount)`

можно делать вызовы функций до построения строки в шаблоне, вычисления отдельно, а не при передаче в аргументы
у тебя все программирование в одной строке)

2021-09-02 22:57 UTC, zelflod commented on source/tree.js
> +    res += `${'|'.padStart((maxWidth + 1) / 2, ' ').padEnd(maxWidth)}\n`;
строка сложная, вынеси вычисления/раздели логику/упрости

2021-09-02 22:57 UTC, zelflod commented on source/tree.js
> +    res += `${'|'.padStart((maxWidth + 1) / 2, ' ').padEnd(maxWidth)}\n`;
`(maxWidth + 1) / 2`
давай дадим названия результатом всех вычисления и вынесем в переменки

2021-09-02 22:57 UTC, zelflod commented on source/tree.js
> +    return res;
в качестве res можно использовать массив и в конце сджойнить

2021-09-03 16:59 UTC, perlinleo commented
# 👋👋👋👋👋👋👋👋👋👋👋👋👋👋👋👋

- Вынес логику в новую отдельную функцию , для которой дописал новые тесты/jsdoc
- Убрал пример 
- Теперь все строки складываются в массив, который в конце джоинится
- Поменял остальные небольшие штуки

2021-09-04 10:58 UTC, zelflod requested changes

2021-09-04 10:58 UTC, zelflod commented on source/tree.js
> +    const spaces = ' '.repeat(spacesAmount);
`' '`
Вынеси в константу как leafSymbol

2021-09-04 10:58 UTC, zelflod commented on source/tree.js
> +    return spaces + string + spaces;
Почему бы не использовать шаблонные строки, как ты делал ранее

2021-09-04 10:58 UTC, zelflod commented on source/tree.js
> +    if (height < 3 || !Number.isInteger(height) || isNaN(height)) {
3 - что за магическая константа?) Дай название

2021-09-04 10:58 UTC, zelflod commented on source/tree.js
> +    result.push(padSpaces('|', maxWidth) + '\n');
Вынеси `|` и `\n` в константы и ответь на вопросы почему так надо делать

2021-09-04 10:58 UTC, zelflod commented on source/tree.js
> +        result.push(padSpaces(core, maxWidth));
Напиши мне в телегу, zelflod

2021-09-04 11:50 UTC, perlinleo commented on source/tree.js
> +        result.push(padSpaces(core, maxWidth));
Отписал

2021-09-04 16:34 UTC, zelflod requested changes

2021-09-04 16:34 UTC, zelflod commented on source/tree.js
> +    return result.join('\n');
почему бы не использовать `layerEnd`?

2021-09-04 16:34 UTC, zelflod commented on source/tree.js
> +        result.push(padSpaces(core, maxWidth));
padSpaces  может вернуть null, а проверки тут нет

2021-09-05 14:55 UTC, zelflod approved these changes

2021-09-05 15:02 UTC, closed without merging