Рьянов Вячеслав
frontend-park-mail-ru/homework_2021_2 pull request #7
Opened 2021-08-26 19:21 UTC by vr009

Рьянов Вячеслав
18 вариант

2021-08-28 15:37 UTC, Slava-Romanov requested changes
Привет! Добро пожаловать на курс по фронтенду :) Сейчас я буду проверять твое нулевое дз. Если возникнут вопросы, не стесняйся, пиши в тг: @Slava_Romanov

2021-08-28 15:37 UTC, Slava-Romanov commented on source/solve.js
> +    return eval(str)
Eval использовать не безопасно. Давай попробуем найти способ решить эту задачу по-другому)

2021-08-28 15:37 UTC, Slava-Romanov commented on source/solve.js
> +function solve(str, x) {
Почему ты используешь такой метод объявления функции, может стоит использовать другой?

2021-08-28 15:37 UTC, Slava-Romanov commented on source/solve.js
> +function solve(str, x) {
Для того, чтобы любому быстро было понятно, что делает функция, ее описывают с помощью JSDoc. Добавим добавим его

2021-08-28 15:38 UTC, Slava-Romanov commented on source/solve.js
> +    str.replace("/x/g",x)
В конце строки лучше ставить точку с запятой

2021-08-30 15:49 UTC, vr009 commented on source/solve.js
> +    return eval(str)
Привет, попробовал сделать через замыкание)

2021-08-30 15:50 UTC, vr009 commented on source/solve.js
> +function solve(str, x) {
Добавил

2021-08-30 17:36 UTC, Slava-Romanov requested changes

2021-08-30 17:36 UTC, Slava-Romanov commented on source/solve.js
> +    return Function('return ' + str)()
К сожалению, использование Function так же небезопасно, попробуй решить эту задачу без eval и Function

2021-08-30 17:36 UTC, Slava-Romanov commented on source/solve.js
> +    str = str.replaceAll("x",x);
Что будет, если входные данные будут некорректными?

2021-08-30 17:36 UTC, Slava-Romanov commented on source/solve.js
> +    return Function('return ' + str)()
Кажется тут должна быть точка с запятой (более подробно прочитать про стиль кода можно тут: https://learn.javascript.ru/coding-style)

2021-08-30 17:36 UTC, Slava-Romanov commented on source/solve.js
> +/**
Давай перейдем в строгий режим (https://learn.javascript.ru/strict-mode)

2021-08-30 17:36 UTC, Slava-Romanov commented on source/solve.js
> +    return Function('return ' + str)()
Представленный код не совсем замыкание.
Замыкание - создание функции, запоминающей свое окружение (более подробно о замыканиях можно прочитать здесь https://learn.javascript.ru/closure)

2021-08-31 17:33 UTC, vr009 commented on source/solve.js
> +    str = str.replaceAll("x",x);
добавил проверку некорректных строк через регулярки и стек скобок

2021-08-31 20:44 UTC, Slava-Romanov requested changes

2021-08-31 20:44 UTC, Slava-Romanov commented on tests/solve.js
> +	QUnit.test('solve c отрицательными числами работает правильно ', function (assert) {
А также тесты на то, что будет, если будут лишние пробелы между знакам и цифрой

2021-08-31 20:44 UTC, Slava-Romanov commented on tests/solve.js
> +	QUnit.test('solve c отрицательными числами работает правильно ', function (assert) {
При входном выражении '1 / 5' кажется не работает корректно?

2021-08-31 20:44 UTC, Slava-Romanov commented on source/solve.js
> +}
Все еще не хватает точек с запятой, где-то не стоят пробелы между аргументами функции, есть лишние enter-ы

2021-08-31 20:44 UTC, Slava-Romanov commented on source/solve.js
> +        if(el === "("){
не хватает пробела

2021-08-31 20:44 UTC, Slava-Romanov commented on source/solve.js
> +const tokenize = (str) =>{
нужна проверка на тип входных данных

2021-08-31 20:44 UTC, Slava-Romanov commented on source/solve.js
> +    str.forEach(function (char, idx) {
function или стрелочная функция?)

2021-08-31 20:44 UTC, Slava-Romanov commented on source/solve.js
> +        let res = substr[idx] === "+"? parseInt(substr[idx - 1]) + parseInt(substr[idx + 1])
кажется это строка записана слишком сложно?

2021-08-31 20:44 UTC, Slava-Romanov commented on source/solve.js
> +const subSolve = (substr,start,end) => {
для substr нужна проверка типа данных, для start/end тоже

2021-08-31 20:44 UTC, Slava-Romanov commented on source/solve.js
> +        }else if (str[idx] === "-" && /\+|-|\*|\/|\^/.test(char) ){
Давай определим один стиль кавычек во всех файлах ДЗ. Обычно предпочитают одинарные

2021-08-31 20:44 UTC, Slava-Romanov commented on source/solve.js
> + * @description Функция для разбора арифметического выражения
Не хватет return

2021-08-31 22:34 UTC, vr009 commented on source/solve.js
> +    substr = substr.slice(start,end+1);
Да, я думаю это не очень хорошая практика, так как js в аргумент копируется ссылка на объект, а это значит что внутри функции мы меняем сам объект вместо копии.

2021-08-31 22:38 UTC, vr009 commented on source/solve.js
> +    str.forEach(function (char, idx) {
Я пошел читать в чем фишка стрелочных функций)

2021-08-31 22:40 UTC, vr009 commented on tests/solve.js
> +	QUnit.test('solve c отрицательными числами работает правильно ', function (assert) {
В условии задания было написано, что без уравнения не содержат знака деления, в тестах такие выражения идут как некорректные, тесты на лишние пробелы добавил и на некорректные данные

2021-08-31 22:40 UTC, vr009 commented on source/solve.js
> + * @description Функция для разбора арифметического выражения
Добавил)

2021-09-01 22:32 UTC, Slava-Romanov requested changes
Общий комментарий:
- Требуется навести порядок по всему код-стайлу всех файлов (пробелы, точки с запятыми, наименование переменных (чтобы по названию было понятно, что там лежит), использовать один стиль кавычек)
- Еще раз посмотреть на все let – точно ли let?
- Упростить код (что-то делается очень сложно, код сложно воспринять), сделать решение более понятным
- Вынести в константы неизменяемые выражения типа regex
- Проверить случаи с некорректными данными тщательнее
- Добавить ошибки функции solve через throw
- Посмотреть нельзя ли заменить for(){} на foreach в некоторых случаях

2021-09-02 22:30 UTC, vr009 commented on source/solve.js
> +    const res = !/\[|\]|\/|\^|[a-w]|[y-z]/.test(str);
затупил, добавил исключающую регулярку и занес в константу

2021-09-02 22:33 UTC, vr009 commented on source/solve.js
> +        let idx = sumIdx.pop();
тут немного переписал функцию, но старался использовать let везде, где нужна была область видимости на уровне скобок, ну или там где область видимости на уровне скобок и функции совпадают

2021-09-02 22:34 UTC, vr009 commented on source/solve.js
> +    for (const el of str) {
да, так проще)

2021-09-04 10:30 UTC, Slava-Romanov requested changes
solve('(+)', 2) - NaN
solve('(x+x)', 'фы') - NaN
solve('xx x', 4) - 444
solve('xx (x)', 4) - 44

Так же в JSDoc, если функция возвращает null, лучше написать @return{Number|null} если вот это, то Number, иначе null

2021-09-04 10:30 UTC, Slava-Romanov commented on source/solve.js
> +        } else return null;
Блок else в целом не нужен, так как компилятор не дойдет до него, если случится return в if

2021-09-04 10:30 UTC, Slava-Romanov commented on source/solve.js
> +    const regexp = /\+|-|\*|\/|\^/;
Лучше все regex и errors вынести на самый вверх файла и именовать заглавными буквами –  {name}_REGEX, {name}_ERROR

2021-09-04 10:30 UTC, Slava-Romanov commented on source/solve.js
> +        } else if (/\+|-|\*|\/|\^/.test(char)) {
в константу

2021-09-04 10:30 UTC, Slava-Romanov commented on source/solve.js
> +}
После стрелочной функции ставится точка с запятой

2021-09-04 10:30 UTC, Slava-Romanov commented on source/solve.js
> +    var scopesCount = 0;
var?

2021-09-04 10:30 UTC, Slava-Romanov commented on source/solve.js
> +        throw new Error('ZeroStringError');
в константу

2021-09-04 10:30 UTC, Slava-Romanov commented on source/solve.js
> +
лишний пробел

2021-09-04 10:30 UTC, Slava-Romanov commented on source/solve.js
> +            res = exprArr[idx] === '+' ? parseInt(exprArr[idx - 1]) + parseInt(exprArr[idx + 1]) :
здесь не очень много преобразований parseInt?

2021-09-04 10:30 UTC, Slava-Romanov commented on source/solve.js
> +            alert('No Expression found');
alert необходимо убрать

2021-09-04 10:30 UTC, Slava-Romanov commented on source/solve.js
> +        if (scopeValidation(str)) {
throw new лучше использовать только в solve – if (!scopeValidation) { throw new Error(EXPRESSION_ERROR); }

2021-09-04 10:30 UTC, Slava-Romanov commented on source/solve.js
> +        if (scopeValidation(str)) {
x тоже можно проверить, не делая замен: проверили выражение, затем проверили корректность x

2021-09-04 10:30 UTC, Slava-Romanov commented on source/solve.js
> +            for (const el of rest) {
 Почему бы не использовать map в этом и других случаях

2021-09-04 10:30 UTC, Slava-Romanov commented on tests/solve.js
> +		assert.strictEqual(exprParser("( ( 1 + 1 ) + ( 2 + 2 ) ) * ( 1 + 1 )".split(" ")),12);
одинарные кавычки

2021-09-04 10:30 UTC, Slava-Romanov commented on source/solve.js
> +            for (const el of rest) {
или, например, reduce

2021-09-04 10:30 UTC, Slava-Romanov commented on source/solve.js
> +"use strict";
одинарные кавычки

2021-09-04 15:37 UTC, vr009 commented on source/solve.js
> +            for (const el of rest) {
с for of запись лаконичнее, но я переделал в reduce :)

2021-09-04 15:37 UTC, vr009 commented on source/solve.js
> +        if (scopeValidation(str)) {
Добавил проверку на странные иксы

2021-09-04 21:32 UTC, Slava-Romanov requested changes

2021-09-04 21:32 UTC, Slava-Romanov commented on source/solve.js
> +const num_REGEX = /\d/;
Константы обычно пишутся заглавными буквами

2021-09-04 21:32 UTC, Slava-Romanov commented on source/solve.js
> + * @param {int} x - переменная x
int точно есть в jsdoc?

2021-09-04 21:32 UTC, Slava-Romanov commented on source/solve.js
> +    try {
Для каких случаев остался try?

2021-09-04 21:32 UTC, Slava-Romanov commented on source/solve.js
> +        } else throw ZeroString_ERROR;
Здесь нарушение стилей – if – длинная запись, else – короткая

Также обычно пишут так: throw new TypeError(ZEROSTRING_ERROR);
Вместо TypeError могут быть и другие типы ошибок

2021-09-04 21:32 UTC, Slava-Romanov commented on source/solve.js
> +    var numberBuffer = [];
VAR?

2021-09-04 21:32 UTC, Slava-Romanov commented on source/solve.js
> +    let rest = str.slice(end + 1, str.length);
точно let?

2021-09-04 21:32 UTC, Slava-Romanov commented on source/solve.js
> +    str = rest.reduce(function (str, current) {
нужна стрелочная функция

2021-09-04 21:32 UTC, Slava-Romanov commented on source/solve.js
> + * @solve функция решения уравнения с неизвестным x
Название функции точно есть в jsdoc?

2021-09-04 21:32 UTC, Slava-Romanov commented on source/solve.js
> +            let start = indexes.pop();
точно let?

2021-09-04 21:32 UTC, Slava-Romanov commented on source/solve.js
> +    if (!strArr.length || toomuch_x_REGEX.test(strArr) || (!num_REGEX.test(strArr) && !onex_REGEX.test(strArr))) {
не выходит за 80 символов?

2021-09-04 21:32 UTC, Slava-Romanov commented on source/solve.js
> +        return false
точки с запятыми

2021-09-04 21:32 UTC, Slava-Romanov commented on source/solve.js
> +
ENTER лишний

2021-09-04 21:32 UTC, Slava-Romanov commented on source/solve.js
> +    var res;
😭

2021-09-05 18:55 UTC, vr009 commented on source/solve.js
> +    if (!strArr.length || toomuch_x_REGEX.test(strArr) || (!num_REGEX.test(strArr) && !onex_REGEX.test(strArr))) {
нет, но перенёс часть

2021-09-05 18:56 UTC, vr009 commented on source/solve.js
> +            let start = indexes.pop();
да, мне эта переменная нужна только в этой области)

2021-09-05 18:57 UTC, vr009 commented on source/solve.js
> +    var numberBuffer = [];
буфер переменный потому что я его очищаю присваиванием пустого массива

2021-09-05 18:58 UTC, vr009 commented on source/solve.js
> +    try {
для случая плохой валидации и неправильного аргумента?

2021-09-05 18:59 UTC, vr009 commented on source/solve.js
> + * @param {int} x - переменная x
поменял на number

2021-09-05 18:59 UTC, vr009 commented on source/solve.js
> +const num_REGEX = /\d/;
Готово

2021-09-05 20:54 UTC, Slava-Romanov commented on source/solve.js
> +            let start = indexes.pop();
Имелось в виду: чем не устроил const?

2021-09-05 20:55 UTC, Slava-Romanov commented on source/solve.js
> +    var numberBuffer = [];
Var использовать крайне нежелательно, необходимо использовать let/const. Для всех неизменяемых далее данных const обязателен (https://learn.javascript.ru/let-const)

2021-09-05 20:59 UTC, Slava-Romanov requested changes
Прокомментировал некоторые предыдущие issue + добавил новые

2021-09-05 20:59 UTC, Slava-Romanov commented on tests/solve.js
> +		assert.strictEqual(exprParser('( ( 5 + 3 ) * ( 3 + 5 ) ) * 3 * 3'.split(' ')),576);
между аргументами необходим пробел

2021-09-05 20:59 UTC, Slava-Romanov commented on source/solve.js
> +            let a = parseInt(exprArr[idx - 1])
это не const должен быть?

2021-09-05 21:26 UTC, vr009 commented on source/solve.js
> +            let a = parseInt(exprArr[idx - 1])
да, логично чтобы был)

2021-09-05 21:27 UTC, vr009 commented on source/solve.js
> +            let start = indexes.pop();
честно говоря, не подумал о том что стоит в const сделать

2021-09-05 21:34 UTC, Slava-Romanov requested changes

2021-09-05 21:34 UTC, Slava-Romanov commented on source/solve.js
> +    try {
Имеется в виду: здесь нужен try? По идее его тут не должно быть

2021-09-05 21:34 UTC, Slava-Romanov commented on source/solve.js
> +            console.log("Bad argument");
console.log тоже не нужен, throw new error будет говорить об ошибке, мы его "пробрасываем" пользователю

2021-09-06 10:48 UTC, Slava-Romanov requested changes
Написал в тг

2021-09-06 15:37 UTC, Slava-Romanov approved these changes

2021-09-06 16:43 UTC, closed without merging