Турчин Денис
frontend-park-mail-ru/homework_2021_2 pull request #9
Opened 2021-08-26 21:02 UTC by Denactive

2021-08-28 17:20 UTC, Betchika99 requested changes
Привет 👋 Добро пожаловать на курс фронтенда. Ты очень обстоятельно подошёл к первому заданию, но есть несколько замечаний, которые нужно вдумчиво поправить. Также нужно разобраться с тестами, чтобы они были более информативными. Например, можешь проверить какие-то исключительные случаи работы твоей функции. Успехов 💪🏻

2021-08-28 17:20 UTC, Betchika99 commented on source/sort.js
> +    const firstToUpperAndSort = (word) => {
Не очень понятное Название функции. Давай сделаем его более информативным, в идеале оно должно отвечать на вопрос «что делает функция»

2021-08-28 17:20 UTC, Betchika99 commented on source/sort.js
> +        .map( (el) => firstToUpperAndSort(el) )
Давай назовём переменные более информативно

2021-08-28 17:20 UTC, Betchika99 commented on tests/sort.js
> +		// assert.strictEqual(sort('Rrrrrrrr'), 'rrrrrrrr');
Спасибо, что отметил ошибку! Комментарий можно удалить

2021-08-28 17:20 UTC, Betchika99 commented on tests/sort.js
> +		// assert.strictEqual(sort('космический корабль летит на марс'), 'Абклорь Амрс Aн Еиийккмоссч Еилтт');
Молодец, что разобрался! Комментарий можно удалить

2021-08-28 17:20 UTC, Betchika99 commented on tests/sort.js
> +QUnit.module('Кастом-тесты на sort', () => {
можно не добавлять свой модуль, тк это все тесты одной и той же функции

2021-08-28 17:20 UTC, Betchika99 commented on tests/sort.js
> +	QUnit.test('Мучаем функцию sort локалями. Помним порядок букв в русском алфавите. Помним про обратный лексикографический порядок слов', (assert) => {
Тесты должны называться более информативно

2021-08-28 17:20 UTC, Betchika99 commented on tests/sort.js
> +	});
А в чем информативность этого теста? Что он проверяет?

2021-08-30 21:38 UTC, Denactive commented
внес исправления. кодстайл, JSDoc, осознанные тесты

2021-08-30 21:58 UTC, Betchika99 requested changes
Уже гораздо лучше! Осталось немного поправить, и домашка будет выполнена :)

2021-08-30 21:58 UTC, Betchika99 commented on source/sort.js
> +        .sort( (a, b) => a.localeCompare(b) )
отступы между круглыми скобками лишние

2021-08-30 21:58 UTC, Betchika99 commented on source/sort.js
> +    let sorted_word = word.toLocaleLowerCase()
почему let? и почему snake_case? пропустил комментарий по этому поводу выше :(

2021-08-30 21:58 UTC, Betchika99 commented on source/sort.js
> +        .sort( (a, b) => a.localeCompare(b) )
отступы между круглыми скобками лишние

2021-08-30 21:58 UTC, Betchika99 commented on source/sort.js
> +        .map( (el) => sortLettersCap(el) )
добавь более осознанное название переменной

2021-08-30 21:58 UTC, Betchika99 commented on tests/sort.js
> +	QUnit.test('Функция адекватно реагирует на одинаковые слова в т.ч. на произвольные символьные последовательности, где порядок символов неинтуитивен', (assert) => {
давай сократим название тесткейса до части "в т.ч..."

2021-08-31 10:11 UTC, Betchika99 approved these changes

2021-09-01 21:09 UTC, closed without merging